export const translations = {
  en: {
    buttons: {
      support: 'Support', channel: 'Channel', user: 'User', admin: 'Admin', playlist: 'Playlist', owner: 'Owner', developer: 'Developer', back: 'Back', pause: '⏸ Pause', skip: '⏭ Skip', stop: '⏹ Stop', language: '🌐 Language', help: 'Help', settings: 'Settings', chooseLanguage: 'Choose language',
    },
    general: { user: 'User', openingHelp: 'Opening help menu...', unknownHelp: 'Unknown help category.', chooseHelp: 'Choose a help category:', useBack: 'Use the button below to go back.' },
    language: { choose: 'Please choose your language. Your choice will be saved until you change it again.', saved: 'Language saved: {language}', invalid: 'Unsupported language.', current: 'Current language: {language}' },
    start: { text: 'Hello {name},\n\nI am {botName}, a JavaScript Telegram music player.\n\n<b>Supported platforms:</b> YouTube, Spotify, Apple Music, JioSaavn, SoundCloud.\n\nUse the buttons below to explore commands or change your language.' },
    help: { userTitle: 'User Commands', adminTitle: 'Admin Commands', devTitle: 'Developer Commands', ownerTitle: 'Owner Commands', playlistTitle: 'Playlist Commands', userContent: '<b>Playback:</b>\n• <code>/play [song]</code> — Play a track\n• <code>/vplay [song]</code> — Play as video\n\n<b>Utilities:</b>\n• <code>/start</code> — Start the bot\n• <code>/language</code> — Change language\n• <code>/privacy</code> — View privacy policy\n• <code>/queue</code> — Show current queue', adminContent: '<b>Controls:</b>\n• <code>/skip</code> — Skip current track\n• <code>/pause</code> — Pause playback\n• <code>/resume</code> — Resume playback\n• <code>/seek [sec]</code> — Seek marker\n\n<b>Queue:</b>\n• <code>/remove [x]</code> — Remove a track\n• <code>/loop [0-10]</code> — Set loop count', devContent: '<b>System:</b>\n• <code>/stats</code> — Show usage statistics\n• <code>/av</code> — Active voice chats', ownerContent: '<b>Maintenance:</b>\n• <code>/broadcast [text]</code> — Broadcast message\n• <code>/logger</code> — Show logger chat\n• <code>/settings</code> — Chat settings', playlistContent: '<b>Management:</b>\n• <code>/createplaylist [name]</code> — Create playlist\n• <code>/deleteplaylist [id]</code> — Delete playlist\n• <code>/addtoplaylist [id] [url]</code> — Add track\n• <code>/removefromplaylist [id] [trackId]</code> — Remove track\n• <code>/playlistinfo [id]</code> — Show playlist\n• <code>/myplaylists</code> — List playlists' },
    playback: { addedToQueue: 'Added to queue: {count}', nowPlaying: 'Now playing', title: 'Title', duration: 'Duration', requestedBy: 'Requested by', duplicate: 'Track already in queue or playing.', downloadFailed: 'Download failed: {error}', queueFull: 'Queue is full (max 10 tracks). Use /end to clear.', playUsage: '<b>Usage:</b>\n/play [song or URL]\n\n<b>Supported Platforms:</b>\n- YouTube\n- Spotify\n- JioSaavn\n- Apple Music\n- SoundCloud', searchingPlaylist: '🔍 Searching playlist...', searchingDownload: '🔍 Searching and downloading...', playlistNotFound: '❌ Playlist not found.', playlistEmpty: '❌ Playlist is empty.', addedPlaylistTracks: '✅ Added {count} track(s) from playlist. Queue length: {length}.', invalidUrl: 'Invalid URL or unsupported platform.\n\nSupported: YouTube, Spotify, JioSaavn, Apple Music, SoundCloud.', fetchError: '❌ Error fetching track info: {error}', noTracks: 'No tracks found.', queueEmpty: 'Queue is empty.', queueTitle: 'Queue:', nothingPlaying: 'Nothing is playing.', skippedNow: 'Skipped: {skipped}\nNow playing: {next}', skippedEnded: 'Skipped: {skipped}\nQueue ended.', stopped: 'Stopped playback and cleared queue.', paused: 'Paused playback.', resumed: 'Resumed playback.', removeUsage: 'Usage: /remove [queue number]', removed: 'Removed: {name}', invalidQueue: 'Invalid queue number.', loopSet: 'Loop count set to {count}.', muted: 'Muted playback.', unmuted: 'Unmuted playback.', speedSet: 'Playback speed set to {speed}x.', noActive: 'No active voice chats.' },
    playlist: { createUsage: 'Usage: /createplaylist [name]', created: '✅ Playlist created.\nName: {name}\nID: <code>{id}</code>', deleteUsage: 'Usage: /deleteplaylist [playlist id]', deleted: '✅ Playlist deleted.', notFound: '❌ Playlist not found.', addUsage: 'Usage: /addtoplaylist [playlist id] [song or URL]', noTrack: 'No track found.', added: '✅ Added {song} to {playlist}.', removeUsage: 'Usage: /removefromplaylist [playlist id] [track id]', removed: '✅ Track removed.', infoUsage: 'Usage: /playlistinfo [playlist id]', empty: 'Empty', none: 'You do not have playlists yet.', trackCount: 'tracks' },
    misc: { pinging: 'Pinging...', pong: 'Pong! {ms} ms', stats: 'Uptime: {uptime}s\nMemory: {memory} MB\nCPU: {cpu} core(s)\nNode: {node}', privacy: 'Privacy: this bot stores chat settings, authorization data, and playlists required for playback. It does not sell user data.', settings: 'Settings\nDefault service: {service}\nSong duration limit: {limit}s\nMax file size: {size} MB\nLanguage: {language}', logger: 'Logger chat: {logger}', notConfigured: 'not configured', ownerBroadcast: 'Only the owner can broadcast.', broadcastPending: 'Broadcast scheduling is preserved in the JavaScript flow; connect a chat registry before sending.', broadcastUsage: 'Usage: /broadcast [text]', ownerShell: 'Only the owner can use shell commands.', shellDisabled: 'Shell execution is disabled in the JavaScript rewrite for safer default deployments.', noop: 'Command accepted. This administrative flow is available as a JavaScript extension point.' },
  },
};

const aliases = {
  id: { buttons: { support: 'Dukungan', channel: 'Kanal', user: 'Pengguna', admin: 'Admin', playlist: 'Playlist', owner: 'Pemilik', developer: 'Developer', back: 'Kembali', pause: '⏸ Jeda', skip: '⏭ Lewati', stop: '⏹ Stop', language: '🌐 Bahasa', help: 'Bantuan', settings: 'Pengaturan', chooseLanguage: 'Pilih bahasa' }, language: { choose: 'Silakan pilih bahasa. Pilihanmu akan disimpan sampai kamu mengubahnya lagi.', saved: 'Bahasa disimpan: {language}', invalid: 'Bahasa tidak didukung.', current: 'Bahasa saat ini: {language}' }, start: { text: 'Halo {name},\n\nSaya {botName}, pemutar musik Telegram berbasis JavaScript.\n\n<b>Platform yang didukung:</b> YouTube, Spotify, Apple Music, JioSaavn, SoundCloud.\n\nGunakan tombol di bawah untuk melihat perintah atau mengubah bahasa.' }, general: { chooseHelp: 'Pilih kategori bantuan:', openingHelp: 'Membuka menu bantuan...', unknownHelp: 'Kategori bantuan tidak dikenal.', useBack: 'Gunakan tombol di bawah untuk kembali.', user: 'Pengguna' }, playback: { nowPlaying: 'Sedang diputar', addedToQueue: 'Ditambahkan ke antrean: {count}', queueEmpty: 'Antrean kosong.', nothingPlaying: 'Tidak ada yang sedang diputar.', stopped: 'Pemutaran dihentikan dan antrean dibersihkan.', paused: 'Pemutaran dijeda.', resumed: 'Pemutaran dilanjutkan.', noTracks: 'Tidak ada lagu ditemukan.', playlistNotFound: '❌ Playlist tidak ditemukan.', playlistEmpty: '❌ Playlist kosong.', duplicate: 'Lagu sudah ada di antrean atau sedang diputar.', queueTitle: 'Antrean:' }, misc: { pinging: 'Menguji...', privacy: 'Privasi: bot ini menyimpan pengaturan chat, data otorisasi, dan playlist yang diperlukan untuk pemutaran. Bot ini tidak menjual data pengguna.', notConfigured: 'belum dikonfigurasi' }, playlist: { notFound: '❌ Playlist tidak ditemukan.', empty: 'Kosong', none: 'Kamu belum memiliki playlist.' } },
  ru: { buttons: { support: 'Поддержка', channel: 'Канал', user: 'Пользователь', admin: 'Админ', playlist: 'Плейлист', owner: 'Владелец', developer: 'Разработчик', back: 'Назад', pause: '⏸ Пауза', skip: '⏭ Пропустить', stop: '⏹ Стоп', language: '🌐 Язык', help: 'Помощь', settings: 'Настройки', chooseLanguage: 'Выбрать язык' }, language: { choose: 'Выберите язык. Выбор сохранится, пока вы не измените его снова.', saved: 'Язык сохранён: {language}', invalid: 'Язык не поддерживается.', current: 'Текущий язык: {language}' }, start: { text: 'Здравствуйте, {name}!\n\nЯ {botName}, музыкальный Telegram-бот на JavaScript.\n\n<b>Поддерживаемые платформы:</b> YouTube, Spotify, Apple Music, JioSaavn, SoundCloud.\n\nИспользуйте кнопки ниже для команд или смены языка.' } },
  ja: { buttons: { support: 'サポート', channel: 'チャンネル', user: 'ユーザー', admin: '管理者', playlist: 'プレイリスト', owner: '所有者', developer: '開発者', back: '戻る', pause: '⏸ 一時停止', skip: '⏭ スキップ', stop: '⏹ 停止', language: '🌐 言語', help: 'ヘルプ', settings: '設定', chooseLanguage: '言語を選択' }, language: { choose: '言語を選択してください。設定は再度変更するまで保存されます。', saved: '言語を保存しました: {language}', invalid: '対応していない言語です。', current: '現在の言語: {language}' }, start: { text: 'こんにちは {name}、\n\n私は {botName}、JavaScript 製の Telegram 音楽プレイヤーです。\n\n<b>対応プラットフォーム:</b> YouTube, Spotify, Apple Music, JioSaavn, SoundCloud.\n\n下のボタンでコマンド確認や言語変更ができます。' } },
  hi: { buttons: { support: 'सहायता', channel: 'चैनल', user: 'यूज़र', admin: 'एडमिन', playlist: 'प्लेलिस्ट', owner: 'Owner', developer: 'डेवलपर', back: 'वापस', pause: '⏸ रोकें', skip: '⏭ छोड़ें', stop: '⏹ बंद', language: '🌐 भाषा', help: 'मदद', settings: 'सेटिंग्स', chooseLanguage: 'भाषा चुनें' }, language: { choose: 'कृपया अपनी भाषा चुनें। यह सेटिंग तब तक सेव रहेगी जब तक आप इसे फिर से नहीं बदलते।', saved: 'भाषा सेव हुई: {language}', invalid: 'यह भाषा समर्थित नहीं है।', current: 'वर्तमान भाषा: {language}' }, start: { text: 'नमस्ते {name},\n\nमैं {botName} हूँ, JavaScript Telegram music player.\n\n<b>समर्थित प्लेटफ़ॉर्म:</b> YouTube, Spotify, Apple Music, JioSaavn, SoundCloud.\n\nकमांड देखने या भाषा बदलने के लिए नीचे दिए बटन इस्तेमाल करें।' } },
  it: { buttons: { support: 'Supporto', channel: 'Canale', user: 'Utente', admin: 'Admin', playlist: 'Playlist', owner: 'Proprietario', developer: 'Sviluppatore', back: 'Indietro', pause: '⏸ Pausa', skip: '⏭ Salta', stop: '⏹ Stop', language: '🌐 Lingua', help: 'Aiuto', settings: 'Impostazioni', chooseLanguage: 'Scegli lingua' }, language: { choose: 'Scegli la tua lingua. La scelta resterà salvata finché non la cambierai di nuovo.', saved: 'Lingua salvata: {language}', invalid: 'Lingua non supportata.', current: 'Lingua attuale: {language}' }, start: { text: 'Ciao {name},\n\nSono {botName}, un player musicale Telegram in JavaScript.\n\n<b>Piattaforme supportate:</b> YouTube, Spotify, Apple Music, JioSaavn, SoundCloud.\n\nUsa i pulsanti qui sotto per esplorare i comandi o cambiare lingua.' } },
  es: { buttons: { support: 'Soporte', channel: 'Canal', user: 'Usuario', admin: 'Admin', playlist: 'Playlist', owner: 'Dueño', developer: 'Desarrollador', back: 'Atrás', pause: '⏸ Pausa', skip: '⏭ Saltar', stop: '⏹ Detener', language: '🌐 Idioma', help: 'Ayuda', settings: 'Ajustes', chooseLanguage: 'Elegir idioma' }, language: { choose: 'Elige tu idioma. Tu elección se guardará hasta que la cambies de nuevo.', saved: 'Idioma guardado: {language}', invalid: 'Idioma no compatible.', current: 'Idioma actual: {language}' }, start: { text: 'Hola {name},\n\nSoy {botName}, un reproductor de música de Telegram en JavaScript.\n\n<b>Plataformas compatibles:</b> YouTube, Spotify, Apple Music, JioSaavn, SoundCloud.\n\nUsa los botones de abajo para ver comandos o cambiar el idioma.' } },
  fr: { buttons: { support: 'Support', channel: 'Canal', user: 'Utilisateur', admin: 'Admin', playlist: 'Playlist', owner: 'Propriétaire', developer: 'Développeur', back: 'Retour', pause: '⏸ Pause', skip: '⏭ Passer', stop: '⏹ Stop', language: '🌐 Langue', help: 'Aide', settings: 'Paramètres', chooseLanguage: 'Choisir la langue' }, language: { choose: 'Choisissez votre langue. Elle restera enregistrée jusqu’à ce que vous la changiez.', saved: 'Langue enregistrée : {language}', invalid: 'Langue non prise en charge.', current: 'Langue actuelle : {language}' }, start: { text: 'Bonjour {name},\n\nJe suis {botName}, un lecteur de musique Telegram en JavaScript.\n\n<b>Plateformes prises en charge :</b> YouTube, Spotify, Apple Music, JioSaavn, SoundCloud.\n\nUtilisez les boutons ci-dessous pour voir les commandes ou changer la langue.' } },
  de: { buttons: { support: 'Support', channel: 'Kanal', user: 'Nutzer', admin: 'Admin', playlist: 'Playlist', owner: 'Besitzer', developer: 'Entwickler', back: 'Zurück', pause: '⏸ Pause', skip: '⏭ Überspringen', stop: '⏹ Stopp', language: '🌐 Sprache', help: 'Hilfe', settings: 'Einstellungen', chooseLanguage: 'Sprache wählen' }, language: { choose: 'Bitte wähle deine Sprache. Die Auswahl bleibt gespeichert, bis du sie wieder änderst.', saved: 'Sprache gespeichert: {language}', invalid: 'Nicht unterstützte Sprache.', current: 'Aktuelle Sprache: {language}' }, start: { text: 'Hallo {name},\n\nich bin {botName}, ein JavaScript-Telegram-Musikplayer.\n\n<b>Unterstützte Plattformen:</b> YouTube, Spotify, Apple Music, JioSaavn, SoundCloud.\n\nNutze die Buttons unten, um Befehle zu sehen oder die Sprache zu ändern.' } },
  pt: { buttons: { support: 'Suporte', channel: 'Canal', user: 'Usuário', admin: 'Admin', playlist: 'Playlist', owner: 'Dono', developer: 'Desenvolvedor', back: 'Voltar', pause: '⏸ Pausar', skip: '⏭ Pular', stop: '⏹ Parar', language: '🌐 Idioma', help: 'Ajuda', settings: 'Configurações', chooseLanguage: 'Escolher idioma' }, language: { choose: 'Escolha seu idioma. A escolha ficará salva até você alterá-la novamente.', saved: 'Idioma salvo: {language}', invalid: 'Idioma não suportado.', current: 'Idioma atual: {language}' }, start: { text: 'Olá {name},\n\nEu sou {botName}, um player de música do Telegram em JavaScript.\n\n<b>Plataformas suportadas:</b> YouTube, Spotify, Apple Music, JioSaavn, SoundCloud.\n\nUse os botões abaixo para ver comandos ou alterar o idioma.' } },
  ar: { buttons: { support: 'الدعم', channel: 'القناة', user: 'المستخدم', admin: 'المشرف', playlist: 'قائمة التشغيل', owner: 'المالك', developer: 'المطور', back: 'رجوع', pause: '⏸ إيقاف مؤقت', skip: '⏭ تخطي', stop: '⏹ إيقاف', language: '🌐 اللغة', help: 'المساعدة', settings: 'الإعدادات', chooseLanguage: 'اختر اللغة' }, language: { choose: 'اختر لغتك. سيتم حفظ اختيارك حتى تغيّره مرة أخرى.', saved: 'تم حفظ اللغة: {language}', invalid: 'اللغة غير مدعومة.', current: 'اللغة الحالية: {language}' }, start: { text: 'مرحباً {name}،\n\nأنا {botName}، مشغل موسيقى Telegram مبني بـ JavaScript.\n\n<b>المنصات المدعومة:</b> YouTube, Spotify, Apple Music, JioSaavn, SoundCloud.\n\nاستخدم الأزرار أدناه لاستعراض الأوامر أو تغيير اللغة.' } },
  tr: { buttons: { support: 'Destek', channel: 'Kanal', user: 'Kullanıcı', admin: 'Admin', playlist: 'Playlist', owner: 'Sahip', developer: 'Geliştirici', back: 'Geri', pause: '⏸ Duraklat', skip: '⏭ Atla', stop: '⏹ Durdur', language: '🌐 Dil', help: 'Yardım', settings: 'Ayarlar', chooseLanguage: 'Dil seç' }, language: { choose: 'Lütfen dilini seç. Bu seçim tekrar değiştirene kadar saklanır.', saved: 'Dil kaydedildi: {language}', invalid: 'Desteklenmeyen dil.', current: 'Geçerli dil: {language}' }, start: { text: 'Merhaba {name},\n\nBen {botName}, JavaScript Telegram müzik oynatıcısıyım.\n\n<b>Desteklenen platformlar:</b> YouTube, Spotify, Apple Music, JioSaavn, SoundCloud.\n\nKomutları görmek veya dili değiştirmek için aşağıdaki düğmeleri kullan.' } },
  ko: { buttons: { support: '지원', channel: '채널', user: '사용자', admin: '관리자', playlist: '플레이리스트', owner: '소유자', developer: '개발자', back: '뒤로', pause: '⏸ 일시정지', skip: '⏭ 건너뛰기', stop: '⏹ 중지', language: '🌐 언어', help: '도움말', settings: '설정', chooseLanguage: '언어 선택' }, language: { choose: '언어를 선택하세요. 다시 변경할 때까지 저장됩니다.', saved: '언어가 저장되었습니다: {language}', invalid: '지원하지 않는 언어입니다.', current: '현재 언어: {language}' }, start: { text: '안녕하세요 {name},\n\n저는 JavaScript Telegram 음악 플레이어 {botName}입니다.\n\n<b>지원 플랫폼:</b> YouTube, Spotify, Apple Music, JioSaavn, SoundCloud.\n\n아래 버튼으로 명령을 보거나 언어를 변경하세요.' } },
  zh: { buttons: { support: '支持', channel: '频道', user: '用户', admin: '管理员', playlist: '播放列表', owner: '所有者', developer: '开发者', back: '返回', pause: '⏸ 暂停', skip: '⏭ 跳过', stop: '⏹ 停止', language: '🌐 语言', help: '帮助', settings: '设置', chooseLanguage: '选择语言' }, language: { choose: '请选择你的语言。设置会一直保存，直到你再次更改。', saved: '语言已保存：{language}', invalid: '不支持的语言。', current: '当前语言：{language}' }, start: { text: '你好 {name}，\n\n我是 {botName}，一个 JavaScript Telegram 音乐播放器。\n\n<b>支持的平台：</b> YouTube, Spotify, Apple Music, JioSaavn, SoundCloud.\n\n使用下方按钮查看命令或更改语言。' } },
};

function mergeDeep(base, override = {}) {
  const output = { ...base };
  for (const [key, value] of Object.entries(override)) {
    output[key] = value && typeof value === 'object' && !Array.isArray(value)
      ? mergeDeep(base[key] ?? {}, value)
      : value;
  }
  return output;
}

for (const [code, override] of Object.entries(aliases)) {
  translations[code] = mergeDeep(translations.en, override);
}

const phraseOverrides = {
  id: {
    help: { userTitle: 'Perintah Pengguna', adminTitle: 'Perintah Admin', devTitle: 'Perintah Developer', ownerTitle: 'Perintah Pemilik', playlistTitle: 'Perintah Playlist' },
    playback: { title: 'Judul', duration: 'Durasi', requestedBy: 'Diminta oleh', downloadFailed: 'Unduhan gagal: {error}', queueFull: 'Antrean penuh (maks 10 lagu). Gunakan /end untuk membersihkan.', searchingPlaylist: '🔍 Mencari playlist...', searchingDownload: '🔍 Mencari dan mengunduh...', addedPlaylistTracks: '✅ Menambahkan {count} lagu dari playlist. Panjang antrean: {length}.', invalidUrl: 'URL tidak valid atau platform tidak didukung.\n\nDidukung: YouTube, Spotify, JioSaavn, Apple Music, SoundCloud.', fetchError: '❌ Gagal mengambil info lagu: {error}', skippedNow: 'Dilewati: {skipped}\nSekarang diputar: {next}', skippedEnded: 'Dilewati: {skipped}\nAntrean selesai.', removeUsage: 'Penggunaan: /remove [nomor antrean]', removed: 'Dihapus: {name}', invalidQueue: 'Nomor antrean tidak valid.', loopSet: 'Jumlah loop diatur ke {count}.', muted: 'Pemutaran dibisukan.', unmuted: 'Pemutaran tidak dibisukan.', speedSet: 'Kecepatan pemutaran diatur ke {speed}x.', noActive: 'Tidak ada voice chat aktif.' },
    misc: { pong: 'Pong! {ms} md', stats: 'Uptime: {uptime}d\nMemori: {memory} MB\nCPU: {cpu} core\nNode: {node}', settings: 'Pengaturan\nLayanan default: {service}\nBatas durasi lagu: {limit}d\nUkuran file maksimum: {size} MB\nBahasa: {language}', logger: 'Chat logger: {logger}', ownerBroadcast: 'Hanya pemilik yang dapat broadcast.', broadcastUsage: 'Penggunaan: /broadcast [teks]', ownerShell: 'Hanya pemilik yang dapat memakai perintah shell.', shellDisabled: 'Eksekusi shell dinonaktifkan agar deployment default lebih aman.', noop: 'Perintah diterima. Alur administrasi ini tersedia sebagai titik ekstensi JavaScript.' },
    playlist: { createUsage: 'Penggunaan: /createplaylist [nama]', created: '✅ Playlist dibuat.\nNama: {name}\nID: <code>{id}</code>', deleteUsage: 'Penggunaan: /deleteplaylist [id playlist]', deleted: '✅ Playlist dihapus.', addUsage: 'Penggunaan: /addtoplaylist [id playlist] [lagu atau URL]', noTrack: 'Tidak ada lagu ditemukan.', added: '✅ Menambahkan {song} ke {playlist}.', removeUsage: 'Penggunaan: /removefromplaylist [id playlist] [id lagu]', removed: '✅ Lagu dihapus.', infoUsage: 'Penggunaan: /playlistinfo [id playlist]', trackCount: 'lagu' },
  },
  ru: { general: { chooseHelp: 'Выберите категорию помощи:', openingHelp: 'Открываю меню помощи...', unknownHelp: 'Неизвестная категория помощи.', useBack: 'Используйте кнопку ниже, чтобы вернуться.', user: 'Пользователь' }, help: { userTitle: 'Команды пользователя', adminTitle: 'Команды администратора', devTitle: 'Команды разработчика', ownerTitle: 'Команды владельца', playlistTitle: 'Команды плейлистов' }, playback: { nowPlaying: 'Сейчас играет', addedToQueue: 'Добавлено в очередь: {count}', title: 'Название', duration: 'Длительность', requestedBy: 'Запросил', duplicate: 'Трек уже в очереди или играет.', queueEmpty: 'Очередь пуста.', queueTitle: 'Очередь:', nothingPlaying: 'Сейчас ничего не играет.', stopped: 'Воспроизведение остановлено, очередь очищена.', paused: 'Воспроизведение на паузе.', resumed: 'Воспроизведение продолжено.', noTracks: 'Треки не найдены.', playlistNotFound: '❌ Плейлист не найден.', playlistEmpty: '❌ Плейлист пуст.' }, misc: { pinging: 'Пинг...', privacy: 'Конфиденциальность: бот хранит настройки чата, данные авторизации и плейлисты, необходимые для воспроизведения. Он не продаёт данные пользователей.', notConfigured: 'не настроено' }, playlist: { notFound: '❌ Плейлист не найден.', empty: 'Пусто', none: 'У вас пока нет плейлистов.' } },
  ja: { general: { chooseHelp: 'ヘルプカテゴリを選択してください:', openingHelp: 'ヘルプメニューを開いています...', unknownHelp: '不明なヘルプカテゴリです。', useBack: '戻るには下のボタンを使ってください。', user: 'ユーザー' }, help: { userTitle: 'ユーザーコマンド', adminTitle: '管理者コマンド', devTitle: '開発者コマンド', ownerTitle: '所有者コマンド', playlistTitle: 'プレイリストコマンド' }, playback: { nowPlaying: '再生中', addedToQueue: 'キューに追加: {count}', title: 'タイトル', duration: '長さ', requestedBy: 'リクエスト', duplicate: 'この曲は既にキュー内または再生中です。', queueEmpty: 'キューは空です。', queueTitle: 'キュー:', nothingPlaying: '何も再生されていません。', stopped: '再生を停止し、キューをクリアしました。', paused: '再生を一時停止しました。', resumed: '再生を再開しました。', noTracks: '曲が見つかりません。', playlistNotFound: '❌ プレイリストが見つかりません。', playlistEmpty: '❌ プレイリストは空です。' }, misc: { pinging: '確認中...', privacy: 'プライバシー: このボットは再生に必要なチャット設定、認証データ、プレイリストを保存します。ユーザーデータは販売しません。', notConfigured: '未設定' }, playlist: { notFound: '❌ プレイリストが見つかりません。', empty: '空', none: 'まだプレイリストがありません。' } },
  hi: { general: { chooseHelp: 'मदद की श्रेणी चुनें:', openingHelp: 'मदद मेनू खोला जा रहा है...', unknownHelp: 'अज्ञात मदद श्रेणी।', useBack: 'वापस जाने के लिए नीचे वाला बटन इस्तेमाल करें।', user: 'यूज़र' }, help: { userTitle: 'यूज़र कमांड', adminTitle: 'एडमिन कमांड', devTitle: 'डेवलपर कमांड', ownerTitle: 'Owner कमांड', playlistTitle: 'प्लेलिस्ट कमांड' }, playback: { nowPlaying: 'अभी चल रहा है', addedToQueue: 'क्यू में जोड़ा गया: {count}', title: 'शीर्षक', duration: 'अवधि', requestedBy: 'अनुरोधकर्ता', duplicate: 'यह ट्रैक पहले से क्यू में है या चल रहा है।', queueEmpty: 'क्यू खाली है।', queueTitle: 'क्यू:', nothingPlaying: 'कुछ भी नहीं चल रहा है।', stopped: 'प्लेबैक रोका गया और क्यू साफ़ हुआ।', paused: 'प्लेबैक रुका।', resumed: 'प्लेबैक फिर शुरू हुआ।', noTracks: 'कोई ट्रैक नहीं मिला।', playlistNotFound: '❌ प्लेलिस्ट नहीं मिली।', playlistEmpty: '❌ प्लेलिस्ट खाली है।' }, misc: { pinging: 'पिंग...', privacy: 'Privacy: यह bot playback के लिए जरूरी chat settings, authorization data और playlists store करता है। यह user data नहीं बेचता।', notConfigured: 'कॉन्फ़िगर नहीं' }, playlist: { notFound: '❌ प्लेलिस्ट नहीं मिली।', empty: 'खाली', none: 'आपके पास अभी playlist नहीं है।' } },
  it: { general: { chooseHelp: 'Scegli una categoria di aiuto:', openingHelp: 'Apro il menu di aiuto...', unknownHelp: 'Categoria di aiuto sconosciuta.', useBack: 'Usa il pulsante qui sotto per tornare indietro.', user: 'Utente' }, help: { userTitle: 'Comandi utente', adminTitle: 'Comandi admin', devTitle: 'Comandi sviluppatore', ownerTitle: 'Comandi proprietario', playlistTitle: 'Comandi playlist' }, playback: { nowPlaying: 'In riproduzione', addedToQueue: 'Aggiunto alla coda: {count}', title: 'Titolo', duration: 'Durata', requestedBy: 'Richiesto da', duplicate: 'Traccia già in coda o in riproduzione.', queueEmpty: 'La coda è vuota.', queueTitle: 'Coda:', nothingPlaying: 'Nulla in riproduzione.', stopped: 'Riproduzione fermata e coda svuotata.', paused: 'Riproduzione in pausa.', resumed: 'Riproduzione ripresa.', noTracks: 'Nessuna traccia trovata.', playlistNotFound: '❌ Playlist non trovata.', playlistEmpty: '❌ La playlist è vuota.' }, misc: { pinging: 'Ping...', privacy: 'Privacy: questo bot salva impostazioni chat, dati di autorizzazione e playlist necessari alla riproduzione. Non vende dati utente.', notConfigured: 'non configurato' }, playlist: { notFound: '❌ Playlist non trovata.', empty: 'Vuota', none: 'Non hai ancora playlist.' } },
  es: { general: { chooseHelp: 'Elige una categoría de ayuda:', openingHelp: 'Abriendo menú de ayuda...', unknownHelp: 'Categoría de ayuda desconocida.', useBack: 'Usa el botón de abajo para volver.', user: 'Usuario' }, help: { userTitle: 'Comandos de usuario', adminTitle: 'Comandos de admin', devTitle: 'Comandos de desarrollador', ownerTitle: 'Comandos del dueño', playlistTitle: 'Comandos de playlist' }, playback: { nowPlaying: 'Reproduciendo', addedToQueue: 'Añadido a la cola: {count}', title: 'Título', duration: 'Duración', requestedBy: 'Pedido por', duplicate: 'La pista ya está en la cola o reproduciéndose.', queueEmpty: 'La cola está vacía.', queueTitle: 'Cola:', nothingPlaying: 'No hay nada reproduciéndose.', stopped: 'Reproducción detenida y cola limpiada.', paused: 'Reproducción pausada.', resumed: 'Reproducción reanudada.', noTracks: 'No se encontraron pistas.', playlistNotFound: '❌ Playlist no encontrada.', playlistEmpty: '❌ La playlist está vacía.' }, misc: { pinging: 'Haciendo ping...', privacy: 'Privacidad: este bot guarda ajustes de chat, datos de autorización y playlists necesarios para reproducir. No vende datos de usuario.', notConfigured: 'no configurado' }, playlist: { notFound: '❌ Playlist no encontrada.', empty: 'Vacía', none: 'Aún no tienes playlists.' } },
};

for (const [code, override] of Object.entries(phraseOverrides)) {
  translations[code] = mergeDeep(translations[code], override);
}
