export const translations = {
  en: {
    buttons: {
      support: 'Support', channel: 'Channel', source: 'Source', addToGroup: 'Add me to your group', user: 'User', admin: 'Admin', playlist: 'Playlist', owner: 'Owner', developer: 'Developer', back: 'Back', pause: '⏸ Pause', resume: '▶️ Resume', skip: '⏭ Skip', stop: '⏹ Stop', mute: '🔇 Mute', unmute: '🔊 Unmute', addToPlaylist: '➕ Playlist', close: '✖️ Close', language: '🌐 Language', help: 'Help', settings: 'Settings', chooseLanguage: 'Choose language',
    },
    general: { user: 'User', openingHelp: 'Opening help menu...', unknownHelp: 'Unknown help category.', chooseHelp: 'Choose a help category:', useBack: 'Use the button below to go back.' },
    language: { choose: 'Please choose your language. Your choice will be saved until you change it again.', saved: 'Language saved: {language}', invalid: 'Unsupported language.', current: 'Current language: {language}' },
    start: { text: '👋 Hey {name},\nThis is <b>{botName}</b>!\n\n🎧 A music player bot with some awesome and useful features.\n\nℹ️ Click on the help button for more info.' },
    help: { userTitle: 'User Commands', adminTitle: 'Admin Commands', devTitle: 'Developer Commands', ownerTitle: 'Owner Commands', playlistTitle: 'Playlist Commands', userContent: '<b>Playback:</b>\n• <code>/play [song]</code> — Play a track\n• <code>/vplay [song]</code> — Play as video\n\n<b>Utilities:</b>\n• <code>/start</code> — Start the bot\n• <code>/language</code> — Change language\n• <code>/privacy</code> — View privacy policy\n• <code>/queue</code> — Show current queue', adminContent: '<b>Controls:</b>\n• <code>/skip</code> — Skip current track\n• <code>/pause</code> — Pause playback\n• <code>/resume</code> — Resume playback\n• <code>/seek [sec]</code> — Seek marker\n\n<b>Queue:</b>\n• <code>/remove [x]</code> — Remove a track\n• <code>/loop [0-10]</code> — Set loop count', devContent: '<b>System:</b>\n• <code>/stats</code> — Show usage statistics\n• <code>/av</code> — Active voice chats', ownerContent: '<b>Maintenance:</b>\n• <code>/broadcast [text]</code> — Broadcast message\n• <code>/logger</code> — Show logger chat\n• <code>/settings</code> — Chat settings', playlistContent: '<b>Management:</b>\n• <code>/createplaylist [name]</code> — Create playlist\n• <code>/deleteplaylist [id]</code> — Delete playlist\n• <code>/addtoplaylist [id] [url]</code> — Add track\n• <code>/removefromplaylist [id] [trackId]</code> — Remove track\n• <code>/playlistinfo [id]</code> — Show playlist\n• <code>/myplaylists</code> — List playlists' },
    callbacks: { track: 'Track', nowPlaying: 'Now Playing', paused: 'Paused', muted: 'Muted', noActivePlayback: 'There is no active playback.', settingsIgnored: 'Settings callbacks are handled separately.', closingPanel: 'Closing panel.', trackSkipped: 'Track skipped.', playbackStopped: 'Playback stopped.', playbackPaused: 'Playback paused.', playbackResumed: 'Playback resumed.', playbackMuted: 'Playback muted.', playbackUnmuted: 'Playback unmuted.', actionFailed: 'Unable to process playback action.', requestedBy: 'Requested by: {user}', pausedBy: 'Paused by {user}', resumedBy: 'Resumed by {user}', mutedBy: 'Muted by {user}', unmutedBy: 'Unmuted by {user}', defaultPlaylistName: 'My Playlist (TgMusic)', addedToPlaylist: 'Track "{song}" added to playlist "{playlist}".', requesterOnly: 'Only the user who requested this track can use these buttons.' },
    playback: { addedToQueue: 'Added to queue: {count}', nowPlaying: 'Now playing', title: 'Title', duration: 'Duration', requestedBy: 'Requested by', duplicate: 'Track already in queue or playing.', downloadFailed: 'Download failed: {error}', voiceFailed: 'Assistant failed to join/play in voice chat: {error}', voiceChatInactiveWarning: '⚠️ Voice chat is not active in this group yet. Start a voice/video chat first, then play music.', queueFull: 'Queue is full (max {max} tracks). Use /end to clear.', playUsage: '<b>Usage:</b>\n/play [song or URL]\n/play request [song name]\n/play url [direct URL or playlist URL]\n\n<b>Supported Platforms:</b>\n- YouTube\n- Spotify\n- JioSaavn\n- Apple Music\n- SoundCloud', searchingPlaylist: '🔍 Searching playlist...', searchingDownload: '🔍 Searching and downloading...', playlistNotFound: '❌ Playlist not found.', playlistEmpty: '❌ Playlist is empty.', addedPlaylistTracks: '✅ Added {count} track(s) from playlist. Queue length: {length}.', invalidUrl: 'Invalid URL or unsupported platform.\n\nSupported: YouTube, Spotify, JioSaavn, Apple Music, SoundCloud.', fetchError: '❌ Error fetching track info: {error}', noTracks: 'No tracks found.', queueEmpty: 'Queue is empty.', queueTitle: 'Queue:', nothingPlaying: 'Nothing is playing.', skippedNow: 'Skipped: {skipped}\nNow playing: {next}', skippedEnded: 'Skipped: {skipped}\nQueue ended.', queueEnded: 'Music has finished.', stopped: 'Stopped playback and cleared queue.', paused: 'Paused playback.', resumed: 'Resumed playback.', removeUsage: 'Usage: /remove [queue number]', removed: 'Removed: {name}', invalidQueue: 'Invalid queue number.', loopSet: 'Loop count set to {count}.', muted: 'Muted playback.', unmuted: 'Unmuted playback.', speedSet: 'Playback speed set to {speed}x.', noActive: 'No active voice chats.',
      chooseTrack: 'Choose a YouTube result:',
      selectionExpired: 'This YouTube selection has expired. Please search again.',
      selectionOwnerOnly: 'Only the user who searched can choose this result.',
      invalidSelection: 'Invalid YouTube selection.',
      trackSelected: 'Selected result #{number}.',
      downloadingSelected: '⬇️ Downloading selected track: {title}',
      channel: 'Channel',
      views: 'Views',
      upload: 'Upload',
      url: 'URL' },
    auth: { listTitle: 'Authorized Users', none: 'No authorized users found.', groupOnly: 'This command can only be used in groups.', adminOnly: 'You must be an administrator to use this command.', adminVerifyFailed: 'Unable to verify administrator status.', targetRequired: 'Reply to a user or provide a numeric user ID.', already: 'This user is already authorized.', notAuthorized: 'This user is not authorized.', added: 'User {userId} has been authorized.', removed: 'User {userId} has been removed from the authorized list.', addFailed: 'Failed to authorize the user.', removeFailed: 'Failed to remove authorized user.' },
    playlist: { createUsage: 'Usage: /createplaylist [name]', created: '✅ Playlist created.\nName: {name}\nID: <code>{id}</code>', deleteUsage: 'Usage: /deleteplaylist [playlist id]', deleted: '✅ Playlist deleted.', notFound: '❌ Playlist not found.', addUsage: 'Usage: /addtoplaylist [playlist id] [song or URL]', noTrack: 'No track found.', added: '✅ Added {song} to {playlist}.', removeUsage: 'Usage: /removefromplaylist [playlist id] [track id]', removed: '✅ Track removed.', infoUsage: 'Usage: /playlistinfo [playlist id]', empty: 'Empty', none: 'You do not have playlists yet.', trackCount: 'tracks' },
    filters: { botNotAdmin: 'Bot is not an administrator in this chat.\nPlease promote the bot with invite users permission.', botAdminVerifyFailed: 'Unable to verify bot administrator status.', botMissingInvite: 'The bot does not have permission to invite users.', botNotAdminReload: 'Bot is not an administrator in this chat.\nUse /reload to refresh admin cache.', adminRequired: 'You must be an administrator to use this command.', notAuthorized: 'You are not authorized to use this command.', adminActionRequired: 'You must be an administrator to use this action.', actionNotAuthorized: 'You are not authorized to use this action.', playModeAdminOnly: 'Play mode is enabled.\nOnly administrators and authorized users can start playback.' },
    devs: { devOnly: 'Only developers can use this command.', noActiveChats: 'No active chats found.', clearAssistantsDone: 'Removed assistant from {count} chats.', clearAssistantsFailed: 'Failed to clear assistants: {error}', leaveAllStarted: 'Assistant is leaving all chats...', leaveAllDone: "Assistant left {count} chats.", leaveAllFailed: 'Failed to leave all chats: {error}', loggerMissing: 'Please set LOGGER_ID in .env first.', loggerUsage: 'Usage: /logger [enable|disable|on|off]\nCurrent status: {status}', loggerEnabled: 'Logger Enabled', loggerDisabled: 'Logger disabled', loggerInvalid: "Invalid argument. Use 'enable', 'disable', 'on', or 'off'." },
    broadcast: { usage: 'Please reply to a message to broadcast.\n\nUsage:\n/broadcast -chat : groups only\n/broadcast -user : users only\n/broadcast -both : groups + users (default)\n/broadcast -copy : send as copy\n\nExamples:\n/broadcast\n/broadcast -chat\n/broadcast -user -copy', started: 'Broadcast started.', ended: 'Broadcast ended.\nGroups: {groups}\nUsers: {users}', stopped: 'Broadcast stopped.\nGroups: {groups}\nUsers: {users}', stopRequested: 'Broadcast stopped.', noneInProgress: 'No broadcast in progress.', alreadyInProgress: 'A broadcast is already in progress.', noTargets: 'No targets found.', failed: 'Broadcast failed: {error}' },
    misc: { pinging: 'Pinging...', pong: 'Pong! {ms} ms', stats: 'Uptime: {uptime}s\nMemory: {memory} MB\nCPU: {cpu} core(s)\nNode: {node}', privacy: '<b>Privacy Policy for {botName}</b>\n\n1. <b>Data Storage</b>\nWe do not store personal data on your device or track browsing activity.\n\n2. <b>Collection</b>\nWe only collect Telegram user IDs, chat IDs, chat settings, authorization data, and playlists needed to provide music services. We do not store phone numbers or locations.\n\n3. <b>Usage</b>\nData is used strictly for bot functionality. No marketing or commercial use.\n\n4. <b>Sharing</b>\nWe do not sell, trade, or share user data with third parties except Telegram infrastructure required for bot operation.\n\n5. <b>Security</b>\nWe use reasonable safeguards, but no online service is 100% secure.\n\n6. <b>Cookies</b>\n{botName} does not use tracking cookies. Optional YouTube cookies configured by the bot owner are only used for media extraction.\n\n7. <b>Your Rights</b>\nYou can request data deletion or block the bot to revoke access.\n\n8. <b>Updates</b>\nPolicy changes will be announced in the bot.\n\n9. <b>Contact</b>\nQuestions? Contact our {support}.\n\n──────────────────\nNote: This policy ensures a safe and respectful experience with {botName}.', settings: 'Settings\nDefault service: {service}\nSong duration limit: {limit}s\nMax file size: {size} MB\nLanguage: {language}', logger: 'Logger chat: {logger}', notConfigured: 'not configured', ownerBroadcast: 'Only the owner can broadcast.', broadcastPending: 'Broadcast scheduling is preserved in the JavaScript flow; connect a chat registry before sending.', broadcastUsage: 'Usage: /broadcast [text]', ownerShell: 'Only the owner can use shell commands.', shellDisabled: 'Shell execution is disabled in the JavaScript rewrite for safer default deployments.', noop: 'Command accepted. This administrative flow is available as a JavaScript extension point.' },
    premium: { ownerOnly: 'Only the owner can manage premium.', grantUsage: 'Usage: /premiumgrant [user|chat] [id] [days=30]', revokeUsage: 'Usage: /premiumrevoke [user|chat] [id]', infoUsage: 'Usage: /premiuminfo [user|chat] [id]', granted: '✅ Premium granted for {scope} <code>{id}</code> until {expires}.', revoked: '✅ Premium revoked for {scope} <code>{id}</code>.', notFound: 'No premium data found for {scope} <code>{id}</code>.', notActiveFeature: 'This feature is only available for active premium user/chat.', info: 'Premium {scope} <code>{id}</code>\nStatus: <b>{status}</b>\nExpires: <b>{expires}</b>', features: '<b>Premium Features</b>\n\n1) Priority Quality & Performance\n• Priority queue processing\n• Faster playback command lane\n• Better reconnect stability\n\n2) Better Audio Experience\n• Premium audio presets\n• Crossfade support\n• Volume normalization\n\n3) Advanced Queue & Playlist\n• Higher queue limit\n• More saved playlists\n• Smart continuation\n\n4) Social / Community\n• Better vote-skip rule\n• DJ role mode\n• Anti-spam request\n• Event mode' },
    admin: { groupOnly: 'This command can only be used in groups.', reloadWait: 'Please wait {time} before using this command again.', reloadStarted: 'Reloading administrator cache...', reloadSuccess: 'Administrator cache reloaded successfully. Cached {count} admin(s).', reloadFailed: 'Failed to reload administrator cache: {error}' },
  },
};

const aliases = {
  id: { buttons: { support: 'Dukungan', channel: 'Kanal', user: 'Pengguna', admin: 'Admin', playlist: 'Playlist', owner: 'Pemilik', developer: 'Developer', back: 'Kembali', pause: '⏸ Jeda', skip: '⏭ Lewati', stop: '⏹ Stop', language: '🌐 Bahasa', help: 'Bantuan', settings: 'Pengaturan', chooseLanguage: 'Pilih bahasa' }, language: { choose: 'Silakan pilih bahasa. Pilihanmu akan disimpan sampai kamu mengubahnya lagi.', saved: 'Bahasa disimpan: {language}', invalid: 'Bahasa tidak didukung.', current: 'Bahasa saat ini: {language}' }, start: { text: 'Halo {name},\n\nSaya {botName}, pemutar musik Telegram berbasis JavaScript.\n\n<b>Platform yang didukung:</b> YouTube, Spotify, Apple Music, JioSaavn, SoundCloud.\n\nGunakan tombol di bawah untuk melihat perintah atau mengubah bahasa.' }, general: { chooseHelp: 'Pilih kategori bantuan:', openingHelp: 'Membuka menu bantuan...', unknownHelp: 'Kategori bantuan tidak dikenal.', useBack: 'Gunakan tombol di bawah untuk kembali.', user: 'Pengguna' }, playback: { nowPlaying: 'Sedang diputar', addedToQueue: 'Ditambahkan ke antrean: {count}', queueEmpty: 'Antrean kosong.', nothingPlaying: 'Tidak ada yang sedang diputar.', stopped: 'Pemutaran dihentikan dan antrean dibersihkan.', paused: 'Pemutaran dijeda.', resumed: 'Pemutaran dilanjutkan.', noTracks: 'Tidak ada lagu ditemukan.', playlistNotFound: '❌ Playlist tidak ditemukan.', playlistEmpty: '❌ Playlist kosong.', duplicate: 'Lagu sudah ada di antrean atau sedang diputar.', queueTitle: 'Antrean:', queueEnded: 'Musik telah selesai.', searchingDownload: '🔍 Mencari dan mengunduh...', chooseTrack: 'Pilih hasil YouTube:', downloadingSelected: '⬇️ Mengunduh trek terpilih: {title}', channel: 'Channel', views: 'Dilihat', upload: 'Diunggah', url: 'URL' }, misc: { pinging: 'Menguji...', privacy: 'Privasi: bot ini menyimpan pengaturan chat, data otorisasi, dan playlist yang diperlukan untuk pemutaran. Bot ini tidak menjual data pengguna.', notConfigured: 'belum dikonfigurasi' }, playlist: { notFound: '❌ Playlist tidak ditemukan.', empty: 'Kosong', none: 'Kamu belum memiliki playlist.' }, callbacks: { requesterOnly: 'Hanya pengguna yang request lagu ini yang bisa memakai tombol ini.' } },
  ru: { buttons: { support: 'Поддержка', channel: 'Канал', user: 'Пользователь', admin: 'Админ', playlist: 'Плейлист', owner: 'Владелец', developer: 'Разработчик', back: 'Назад', pause: '⏸ Пауза', skip: '⏭ Пропустить', stop: '⏹ Стоп', language: '🌐 Язык', help: 'Помощь', settings: 'Настройки', chooseLanguage: 'Выбрать язык' }, language: { choose: 'Выберите язык. Выбор сохранится, пока вы не измените его снова.', saved: 'Язык сохранён: {language}', invalid: 'Язык не поддерживается.', current: 'Текущий язык: {language}' }, start: { text: 'Здравствуйте, {name}!\n\nЯ {botName}, музыкальный Telegram-бот на JavaScript.\n\n<b>Поддерживаемые платформы:</b> YouTube, Spotify, Apple Music, JioSaavn, SoundCloud.\n\nИспользуйте кнопки ниже для команд или смены языка.' } },
  ja: { buttons: { support: 'サポート', channel: 'チャンネル', user: 'ユーザー', admin: '管理者', playlist: 'プレイリスト', owner: '所有者', developer: '開発者', back: '戻る', pause: '⏸ 一時停止', skip: '⏭ スキップ', stop: '⏹ 停止', language: '🌐 言語', help: 'ヘルプ', settings: '設定', chooseLanguage: '言語を選択' }, language: { choose: '言語を選択してください。設定は再度変更するまで保存されます。', saved: '言語を保存しました: {language}', invalid: '対応していない言語です。', current: '現在の言語: {language}' }, start: { text: 'こんにちは {name}、\n\n私は {botName}、JavaScript 製の Telegram 音楽プレイヤーです。\n\n<b>対応プラットフォーム:</b> YouTube, Spotify, Apple Music, JioSaavn, SoundCloud.\n\n下のボタンでコマンド確認や言語変更ができます。' } },
  hi: { buttons: { support: 'सहायता', channel: 'चैनल', user: 'यूज़र', admin: 'एडमिन', playlist: 'प्लेलिस्ट', owner: 'Owner', developer: 'डेवलपर', back: 'वापस', pause: '⏸ रोकें', skip: '⏭ छोड़ें', stop: '⏹ बंद', language: '🌐 भाषा', help: 'मदद', settings: 'सेटिंग्स', chooseLanguage: 'भाषा चुनें' }, language: { choose: 'कृपया अपनी भाषा चुनें। यह सेटिंग तब तक सेव रहेगी जब तक आप इसे फिर से नहीं बदलते।', saved: 'भाषा सेव हुई: {language}', invalid: 'यह भाषा समर्थित नहीं है।', current: 'वर्तमान भाषा: {language}' }, start: { text: 'नमस्ते {name},\n\nमैं {botName} हूँ, JavaScript Telegram music player.\n\n<b>समर्थित प्लेटफ़ॉर्म:</b> YouTube, Spotify, Apple Music, JioSaavn, SoundCloud.\n\nकमांड देखने या भाषा बदलने के लिए नीचे दिए बटन इस्तेमाल करें।' } },
  it: { buttons: { support: 'Supporto', channel: 'Canale', user: 'Utente', admin: 'Admin', playlist: 'Playlist', owner: 'Proprietario', developer: 'Sviluppatore', back: 'Indietro', pause: '⏸ Pausa', skip: '⏭ Salta', stop: '⏹ Stop', language: '🌐 Lingua', help: 'Aiuto', settings: 'Impostazioni', chooseLanguage: 'Scegli lingua' }, language: { choose: 'Scegli la tua lingua. La scelta resterà salvata finché non la cambierai di nuovo.', saved: 'Lingua salvata: {language}', invalid: 'Lingua non supportata.', current: 'Lingua attuale: {language}' }, start: { text: 'Ciao {name},\n\nSono {botName}, un player musicale Telegram in JavaScript.\n\n<b>Piattaforme supportate:</b> YouTube, Spotify, Apple Music, JioSaavn, SoundCloud.\n\nUsa i pulsanti qui sotto per esplorare i comandi o cambiare lingua.' } },
  es: { buttons: { support: 'Soporte', channel: 'Canal', user: 'Usuario', admin: 'Admin', playlist: 'Playlist', owner: 'Dueño', developer: 'Desarrollador', back: 'Atrás', pause: '⏸ Pausa', skip: '⏭ Saltar', stop: '⏹ Detener', language: '🌐 Idioma', help: 'Ayuda', settings: 'Ajustes', chooseLanguage: 'Elegir idioma' }, language: { choose: 'Elige tu idioma. Tu elección se guardará hasta que la cambies de nuevo.', saved: 'Idioma guardado: {language}', invalid: 'Idioma no compatible.', current: 'Idioma actual: {language}' }, start: { text: 'Hola {name},\n\nSoy {botName}, un reproductor de música de Telegram en JavaScript.\n\n<b>Plataformas compatibles:</b> YouTube, Spotify, Apple Music, JioSaavn, SoundCloud.\n\nUsa los botones de abajo para ver comandos o cambiar el idioma.' } },
  fr: { buttons: { support: 'Support', channel: 'Canal', user: 'Utilisateur', admin: 'Admin', playlist: 'Playlist', owner: 'Propriétaire', developer: 'Développeur', back: 'Retour', pause: '⏸ Pause', skip: '⏭ Passer', stop: '⏹ Stop', language: '🌐 Langue', help: 'Aide', settings: 'Paramètres', chooseLanguage: 'Choisir la langue' }, language: { choose: 'Choisissez votre langue. Elle restera enregistrée jusqu’à ce que vous la changiez.', saved: 'Langue enregistrée : {language}', invalid: 'Langue non prise en charge.', current: 'Langue actuelle : {language}' }, start: { text: 'Bonjour {name},\n\nJe suis {botName}, un lecteur de musique Telegram en JavaScript.\n\n<b>Plateformes prises en charge :</b> YouTube, Spotify, Apple Music, JioSaavn, SoundCloud.\n\nUtilisez les boutons ci-dessous pour voir les commandes ou changer la langue.' } },
  de: { buttons: { support: 'Support', channel: 'Kanal', user: 'Nutzer', admin: 'Admin', playlist: 'Playlist', owner: 'Besitzer', developer: 'Entwickler', back: 'Zurück', pause: '⏸ Pause', skip: '⏭ Überspringen', stop: '⏹ Stopp', language: '🌐 Sprache', help: 'Hilfe', settings: 'Einstellungen', chooseLanguage: 'Sprache wählen' }, language: { choose: 'Bitte wähle deine Sprache. Die Auswahl bleibt gespeichert, bis du sie wieder änderst.', saved: 'Sprache gespeichert: {language}', invalid: 'Nicht unterstützte Sprache.', current: 'Aktuelle Sprache: {language}' }, start: { text: 'Hallo {name},\n\nich bin {botName}, ein JavaScript-Telegram-Musikplayer.\n\n<b>Unterstützte Plattformen:</b> YouTube, Spotify, Apple Music, JioSaavn, SoundCloud.\n\nNutze die Buttons unten, um Befehle zu sehen oder die Sprache zu ändern.' } },
  pt: { buttons: { support: 'Suporte', channel: 'Canal', user: 'Usuário', admin: 'Admin', playlist: 'Playlist', owner: 'Dono', developer: 'Desenvolvedor', back: 'Voltar', pause: '⏸ Pausar', skip: '⏭ Pular', stop: '⏹ Parar', language: '🌐 Idioma', help: 'Ajuda', settings: 'Configurações', chooseLanguage: 'Escolher idioma' }, language: { choose: 'Escolha seu idioma. A escolha ficará salva até você alterá-la novamente.', saved: 'Idioma salvo: {language}', invalid: 'Idioma não suportado.', current: 'Idioma atual: {language}' }, start: { text: 'Olá {name},\n\nEu sou {botName}, um player de música do Telegram em JavaScript.\n\n<b>Plataformas suportadas:</b> YouTube, Spotify, Apple Music, JioSaavn, SoundCloud.\n\nUse os botões abaixo para ver comandos ou alterar o idioma.' } },
  ar: { buttons: { support: 'الدعم', channel: 'القناة', user: 'المستخدم', admin: 'المشرف', playlist: 'قائمة التشغيل', owner: 'المالك', developer: 'المطور', back: 'رجوع', pause: '⏸ إيقاف مؤقت', skip: '⏭ تخطي', stop: '⏹ إيقاف', language: '🌐 اللغة', help: 'المساعدة', settings: 'الإعدادات', chooseLanguage: 'اختر اللغة' }, language: { choose: 'اختر لغتك. سيتم حفظ اختيارك حتى تغيّره مرة أخرى.', saved: 'تم حفظ اللغة: {language}', invalid: 'اللغة غير مدعومة.', current: 'اللغة الحالية: {language}' }, start: { text: 'مرحباً {name}،\n\nأنا {botName}، مشغل موسيقى Telegram مبني بـ JavaScript.\n\n<b>المنصات المدعومة:</b> YouTube, Spotify, Apple Music, JioSaavn, SoundCloud.\n\nاستخدم الأزرار أدناه لاستعراض الأوامر أو تغيير اللغة.' } },
  tr: { buttons: { support: 'Destek', channel: 'Kanal', user: 'Kullanıcı', admin: 'Admin', playlist: 'Playlist', owner: 'Sahip', developer: 'Geliştirici', back: 'Geri', pause: '⏸ Duraklat', skip: '⏭ Atla', stop: '⏹ Durdur', language: '🌐 Dil', help: 'Yardım', settings: 'Ayarlar', chooseLanguage: 'Dil seç' }, language: { choose: 'Lütfen dilini seç. Bu seçim tekrar değiştirene kadar saklanır.', saved: 'Dil kaydedildi: {language}', invalid: 'Desteklenmeyen dil.', current: 'Geçerli dil: {language}' }, start: { text: 'Merhaba {name},\n\nBen {botName}, JavaScript Telegram müzik oynatıcısıyım.\n\n<b>Desteklenen platformlar:</b> YouTube, Spotify, Apple Music, JioSaavn, SoundCloud.\n\nKomutları görmek veya dili değiştirmek için aşağıdaki düğmeleri kullan.' } },
  ko: { buttons: { support: '지원', channel: '채널', user: '사용자', admin: '관리자', playlist: '플레이리스트', owner: '소유자', developer: '개발자', back: '뒤로', pause: '⏸ 일시정지', skip: '⏭ 건너뛰기', stop: '⏹ 중지', language: '🌐 언어', help: '도움말', settings: '설정', chooseLanguage: '언어 선택' }, language: { choose: '언어를 선택하세요. 다시 변경할 때까지 저장됩니다.', saved: '언어가 저장되었습니다: {language}', invalid: '지원하지 않는 언어입니다.', current: '현재 언어: {language}' }, start: { text: '안녕하세요 {name},\n\n저는 JavaScript Telegram 음악 플레이어 {botName}입니다.\n\n<b>지원 플랫폼:</b> YouTube, Spotify, Apple Music, JioSaavn, SoundCloud.\n\n아래 버튼으로 명령을 보거나 언어를 변경하세요.' } },
  zh: { buttons: { support: '支持', channel: '频道', user: '用户', admin: '管理员', playlist: '播放列表', owner: '所有者', developer: '开发者', back: '返回', pause: '⏸ 暂停', skip: '⏭ 跳过', stop: '⏹ 停止', language: '🌐 语言', help: '帮助', settings: '设置', chooseLanguage: '选择语言' }, language: { choose: '请选择你的语言。设置会一直保存，直到你再次更改。', saved: '语言已保存：{language}', invalid: '不支持的语言。', current: '当前语言：{language}' }, start: { text: '你好 {name}，\n\n我是 {botName}，一个 JavaScript Telegram 音乐播放器。\n\n<b>支持的平台：</b> YouTube, Spotify, Apple Music, JioSaavn, SoundCloud.\n\n使用下方按钮查看命令或更改语言。' } },
};

function mergeDeep(base, override = {}) {
  const output = { ...base };
  for (const [key, value] of Object.entries(override)) {
    output[key] = value && typeof value === 'object' && !Array.isArray(value)
      ? mergeDeep(base[key] ?? {}, value)
      : value;
  }
  return output;
}

for (const [code, override] of Object.entries(aliases)) {
  translations[code] = mergeDeep(translations.en, override);
}

const phraseOverrides = {
  id: {
    help: { userTitle: 'Perintah Pengguna', adminTitle: 'Perintah Admin', devTitle: 'Perintah Developer', ownerTitle: 'Perintah Pemilik', playlistTitle: 'Perintah Playlist' },
    playback: { title: 'Judul', duration: 'Durasi', requestedBy: 'Diminta oleh', downloadFailed: 'Unduhan gagal: {error}', voiceFailed: 'Asisten gagal naik/memutar di obrolan video: {error}', voiceChatInactiveWarning: '🎙️ Obrolan suara belum aktif di grup ini.\n\nSilakan mulai <b>Voice Chat / Video Chat</b> dulu, lalu kirim <b>/play</b> lagi ya ✨', queueFull: 'Antrean penuh (maks 10 lagu). Gunakan /end untuk membersihkan.', searchingPlaylist: '🔍 Mencari playlist...', searchingDownload: '🔍 Mencari dan mengunduh...', addedPlaylistTracks: '✅ Menambahkan {count} lagu dari playlist. Panjang antrean: {length}.', invalidUrl: 'URL tidak valid atau platform tidak didukung.\n\nDidukung: YouTube, Spotify, JioSaavn, Apple Music, SoundCloud.', fetchError: '❌ Gagal mengambil info lagu: {error}', skippedNow: 'Dilewati: {skipped}\nSekarang diputar: {next}', skippedEnded: 'Dilewati: {skipped}\nAntrean selesai.', removeUsage: 'Penggunaan: /remove [nomor antrean]', removed: 'Dihapus: {name}', invalidQueue: 'Nomor antrean tidak valid.', loopSet: 'Jumlah loop diatur ke {count}.', muted: 'Pemutaran dibisukan.', unmuted: 'Pemutaran tidak dibisukan.', speedSet: 'Kecepatan pemutaran diatur ke {speed}x.', noActive: 'Tidak ada voice chat aktif.',
      chooseTrack: 'Pilih hasil YouTube:',
      selectionExpired: 'Pilihan YouTube ini sudah kedaluwarsa. Silakan cari lagi.',
      selectionOwnerOnly: 'Hanya user yang mencari yang bisa memilih hasil ini.',
      invalidSelection: 'Pilihan YouTube tidak valid.',
      trackSelected: 'Memilih hasil #{number}.',
      downloadingSelected: '⬇️ Mengunduh lagu yang dipilih: {title}' },
    misc: { pong: 'Pong! {ms} md', stats: 'Uptime: {uptime}d\nMemori: {memory} MB\nCPU: {cpu} core\nNode: {node}', privacy: '<b>Kebijakan Privasi untuk {botName}</b>\n\n1. <b>Penyimpanan Data</b>\nKami tidak menyimpan data pribadi di perangkatmu atau melacak aktivitas browsing.\n\n2. <b>Pengumpulan</b>\nKami hanya mengumpulkan ID pengguna Telegram, ID chat, pengaturan chat, data otorisasi, dan playlist yang dibutuhkan untuk layanan musik. Kami tidak menyimpan nomor telepon atau lokasi.\n\n3. <b>Penggunaan</b>\nData hanya digunakan untuk fungsi bot. Tidak ada penggunaan marketing atau komersial.\n\n4. <b>Berbagi Data</b>\nKami tidak menjual, menukar, atau membagikan data pengguna ke pihak ketiga kecuali infrastruktur Telegram yang dibutuhkan untuk operasi bot.\n\n5. <b>Keamanan</b>\nKami memakai perlindungan yang wajar, tetapi tidak ada layanan online yang 100% aman.\n\n6. <b>Cookies</b>\n{botName} tidak memakai tracking cookies. Cookies YouTube opsional dari owner bot hanya digunakan untuk ekstraksi media.\n\n7. <b>Hak Kamu</b>\nKamu dapat meminta penghapusan data atau memblokir bot untuk mencabut akses.\n\n8. <b>Pembaruan</b>\nPerubahan kebijakan akan diumumkan di bot.\n\n9. <b>Kontak</b>\nAda pertanyaan? Hubungi {support}.\n\n──────────────────\nCatatan: Kebijakan ini menjaga pengalaman yang aman dan saling menghormati dengan {botName}.', settings: 'Pengaturan\nLayanan default: {service}\nBatas durasi lagu: {limit}d\nUkuran file maksimum: {size} MB\nBahasa: {language}', logger: 'Chat logger: {logger}', ownerBroadcast: 'Hanya pemilik yang dapat broadcast.', broadcastUsage: 'Penggunaan: /broadcast [teks]', ownerShell: 'Hanya pemilik yang dapat memakai perintah shell.', shellDisabled: 'Eksekusi shell dinonaktifkan agar deployment default lebih aman.', noop: 'Perintah diterima. Alur administrasi ini tersedia sebagai titik ekstensi JavaScript.' },
    admin: { groupOnly: 'Perintah ini hanya bisa digunakan di grup.', reloadWait: 'Tunggu {time} sebelum memakai perintah ini lagi.', reloadStarted: 'Memuat ulang cache administrator...', reloadSuccess: 'Cache administrator berhasil dimuat ulang. Menyimpan {count} admin.', reloadFailed: 'Gagal memuat ulang cache administrator: {error}' },
    playlist: { createUsage: 'Penggunaan: /createplaylist [nama]', created: '✅ Playlist dibuat.\nNama: {name}\nID: <code>{id}</code>', deleteUsage: 'Penggunaan: /deleteplaylist [id playlist]', deleted: '✅ Playlist dihapus.', addUsage: 'Penggunaan: /addtoplaylist [id playlist] [lagu atau URL]', noTrack: 'Tidak ada lagu ditemukan.', added: '✅ Menambahkan {song} ke {playlist}.', removeUsage: 'Penggunaan: /removefromplaylist [id playlist] [id lagu]', removed: '✅ Lagu dihapus.', infoUsage: 'Penggunaan: /playlistinfo [id playlist]', trackCount: 'lagu' },
  },
  ru: { general: { chooseHelp: 'Выберите категорию помощи:', openingHelp: 'Открываю меню помощи...', unknownHelp: 'Неизвестная категория помощи.', useBack: 'Используйте кнопку ниже, чтобы вернуться.', user: 'Пользователь' }, help: { userTitle: 'Команды пользователя', adminTitle: 'Команды администратора', devTitle: 'Команды разработчика', ownerTitle: 'Команды владельца', playlistTitle: 'Команды плейлистов' }, playback: { nowPlaying: 'Сейчас играет', addedToQueue: 'Добавлено в очередь: {count}', title: 'Название', duration: 'Длительность', requestedBy: 'Запросил', duplicate: 'Трек уже в очереди или играет.', queueEmpty: 'Очередь пуста.', queueTitle: 'Очередь:', nothingPlaying: 'Сейчас ничего не играет.', stopped: 'Воспроизведение остановлено, очередь очищена.', paused: 'Воспроизведение на паузе.', resumed: 'Воспроизведение продолжено.', noTracks: 'Треки не найдены.', playlistNotFound: '❌ Плейлист не найден.', playlistEmpty: '❌ Плейлист пуст.' }, misc: { pinging: 'Пинг...', privacy: 'Конфиденциальность: бот хранит настройки чата, данные авторизации и плейлисты, необходимые для воспроизведения. Он не продаёт данные пользователей.', notConfigured: 'не настроено' }, playlist: { notFound: '❌ Плейлист не найден.', empty: 'Пусто', none: 'У вас пока нет плейлистов.' } },
  ja: { general: { chooseHelp: 'ヘルプカテゴリを選択してください:', openingHelp: 'ヘルプメニューを開いています...', unknownHelp: '不明なヘルプカテゴリです。', useBack: '戻るには下のボタンを使ってください。', user: 'ユーザー' }, help: { userTitle: 'ユーザーコマンド', adminTitle: '管理者コマンド', devTitle: '開発者コマンド', ownerTitle: '所有者コマンド', playlistTitle: 'プレイリストコマンド' }, playback: { nowPlaying: '再生中', addedToQueue: 'キューに追加: {count}', title: 'タイトル', duration: '長さ', requestedBy: 'リクエスト', duplicate: 'この曲は既にキュー内または再生中です。', queueEmpty: 'キューは空です。', queueTitle: 'キュー:', nothingPlaying: '何も再生されていません。', stopped: '再生を停止し、キューをクリアしました。', paused: '再生を一時停止しました。', resumed: '再生を再開しました。', noTracks: '曲が見つかりません。', playlistNotFound: '❌ プレイリストが見つかりません。', playlistEmpty: '❌ プレイリストは空です。' }, misc: { pinging: '確認中...', privacy: 'プライバシー: このボットは再生に必要なチャット設定、認証データ、プレイリストを保存します。ユーザーデータは販売しません。', notConfigured: '未設定' }, playlist: { notFound: '❌ プレイリストが見つかりません。', empty: '空', none: 'まだプレイリストがありません。' } },
  hi: { general: { chooseHelp: 'मदद की श्रेणी चुनें:', openingHelp: 'मदद मेनू खोला जा रहा है...', unknownHelp: 'अज्ञात मदद श्रेणी।', useBack: 'वापस जाने के लिए नीचे वाला बटन इस्तेमाल करें।', user: 'यूज़र' }, help: { userTitle: 'यूज़र कमांड', adminTitle: 'एडमिन कमांड', devTitle: 'डेवलपर कमांड', ownerTitle: 'Owner कमांड', playlistTitle: 'प्लेलिस्ट कमांड' }, playback: { nowPlaying: 'अभी चल रहा है', addedToQueue: 'क्यू में जोड़ा गया: {count}', title: 'शीर्षक', duration: 'अवधि', requestedBy: 'अनुरोधकर्ता', duplicate: 'यह ट्रैक पहले से क्यू में है या चल रहा है।', queueEmpty: 'क्यू खाली है।', queueTitle: 'क्यू:', nothingPlaying: 'कुछ भी नहीं चल रहा है।', stopped: 'प्लेबैक रोका गया और क्यू साफ़ हुआ।', paused: 'प्लेबैक रुका।', resumed: 'प्लेबैक फिर शुरू हुआ।', noTracks: 'कोई ट्रैक नहीं मिला।', playlistNotFound: '❌ प्लेलिस्ट नहीं मिली।', playlistEmpty: '❌ प्लेलिस्ट खाली है।' }, misc: { pinging: 'पिंग...', privacy: 'Privacy: यह bot playback के लिए जरूरी chat settings, authorization data और playlists store करता है। यह user data नहीं बेचता।', notConfigured: 'कॉन्फ़िगर नहीं' }, playlist: { notFound: '❌ प्लेलिस्ट नहीं मिली।', empty: 'खाली', none: 'आपके पास अभी playlist नहीं है।' } },
  it: { general: { chooseHelp: 'Scegli una categoria di aiuto:', openingHelp: 'Apro il menu di aiuto...', unknownHelp: 'Categoria di aiuto sconosciuta.', useBack: 'Usa il pulsante qui sotto per tornare indietro.', user: 'Utente' }, help: { userTitle: 'Comandi utente', adminTitle: 'Comandi admin', devTitle: 'Comandi sviluppatore', ownerTitle: 'Comandi proprietario', playlistTitle: 'Comandi playlist' }, playback: { nowPlaying: 'In riproduzione', addedToQueue: 'Aggiunto alla coda: {count}', title: 'Titolo', duration: 'Durata', requestedBy: 'Richiesto da', duplicate: 'Traccia già in coda o in riproduzione.', queueEmpty: 'La coda è vuota.', queueTitle: 'Coda:', nothingPlaying: 'Nulla in riproduzione.', stopped: 'Riproduzione fermata e coda svuotata.', paused: 'Riproduzione in pausa.', resumed: 'Riproduzione ripresa.', noTracks: 'Nessuna traccia trovata.', playlistNotFound: '❌ Playlist non trovata.', playlistEmpty: '❌ La playlist è vuota.' }, misc: { pinging: 'Ping...', privacy: 'Privacy: questo bot salva impostazioni chat, dati di autorizzazione e playlist necessari alla riproduzione. Non vende dati utente.', notConfigured: 'non configurato' }, playlist: { notFound: '❌ Playlist non trovata.', empty: 'Vuota', none: 'Non hai ancora playlist.' } },
  es: { general: { chooseHelp: 'Elige una categoría de ayuda:', openingHelp: 'Abriendo menú de ayuda...', unknownHelp: 'Categoría de ayuda desconocida.', useBack: 'Usa el botón de abajo para volver.', user: 'Usuario' }, help: { userTitle: 'Comandos de usuario', adminTitle: 'Comandos de admin', devTitle: 'Comandos de desarrollador', ownerTitle: 'Comandos del dueño', playlistTitle: 'Comandos de playlist' }, playback: { nowPlaying: 'Reproduciendo', addedToQueue: 'Añadido a la cola: {count}', title: 'Título', duration: 'Duración', requestedBy: 'Pedido por', duplicate: 'La pista ya está en la cola o reproduciéndose.', queueEmpty: 'La cola está vacía.', queueTitle: 'Cola:', nothingPlaying: 'No hay nada reproduciéndose.', stopped: 'Reproducción detenida y cola limpiada.', paused: 'Reproducción pausada.', resumed: 'Reproducción reanudada.', noTracks: 'No se encontraron pistas.', playlistNotFound: '❌ Playlist no encontrada.', playlistEmpty: '❌ La playlist está vacía.' }, misc: { pinging: 'Haciendo ping...', privacy: 'Privacidad: este bot guarda ajustes de chat, datos de autorización y playlists necesarios para reproducir. No vende datos de usuario.', notConfigured: 'no configurado' }, playlist: { notFound: '❌ Playlist no encontrada.', empty: 'Vacía', none: 'Aún no tienes playlists.' } },
};

for (const [code, override] of Object.entries(phraseOverrides)) {
  translations[code] = mergeDeep(translations[code], override);
}


const playbackSelectionTranslations = {
  id: { playback: { searchingDownload: '🔍 Mencari dan mengunduh...', chooseTrack: 'Pilih hasil YouTube:', downloadingSelected: '⬇️ Mengunduh lagu yang dipilih: {title}', channel: 'Channel', views: 'Dilihat', upload: 'Diunggah', url: 'URL' } },
  ru: { playback: { searchingDownload: '🔍 Поиск и загрузка...', chooseTrack: 'Выберите результат YouTube:', downloadingSelected: '⬇️ Загружается выбранный трек: {title}', channel: 'Канал', views: 'Просмотры', upload: 'Загрузка', url: 'Ссылка' } },
  ja: { playback: { searchingDownload: '🔍 検索してダウンロード中...', chooseTrack: 'YouTube の結果を選択:', downloadingSelected: '⬇️ 選択したトラックをダウンロード中: {title}', channel: 'チャンネル', views: '再生回数', upload: '公開', url: 'URL' } },
  hi: { playback: { searchingDownload: '🔍 खोज और डाउनलोड किया जा रहा है...', chooseTrack: 'YouTube परिणाम चुनें:', downloadingSelected: '⬇️ चुना गया ट्रैक डाउनलोड हो रहा है: {title}', channel: 'चैनल', views: 'व्यूज़', upload: 'अपलोड', url: 'URL' } },
  it: { playback: { searchingDownload: '🔍 Ricerca e download in corso...', chooseTrack: 'Scegli un risultato YouTube:', downloadingSelected: '⬇️ Download della traccia selezionata: {title}', channel: 'Canale', views: 'Visualizzazioni', upload: 'Caricato', url: 'URL' } },
  es: { playback: { searchingDownload: '🔍 Buscando y descargando...', chooseTrack: 'Elige un resultado de YouTube:', downloadingSelected: '⬇️ Descargando la pista seleccionada: {title}', channel: 'Canal', views: 'Vistas', upload: 'Subido', url: 'URL' } },
  fr: { playback: { searchingDownload: '🔍 Recherche et téléchargement...', chooseTrack: 'Choisissez un résultat YouTube :', downloadingSelected: '⬇️ Téléchargement du morceau sélectionné : {title}', channel: 'Chaîne', views: 'Vues', upload: 'Mise en ligne', url: 'URL' } },
  de: { playback: { searchingDownload: '🔍 Suche und Download...', chooseTrack: 'Wähle ein YouTube-Ergebnis:', downloadingSelected: '⬇️ Ausgewählter Titel wird heruntergeladen: {title}', channel: 'Kanal', views: 'Aufrufe', upload: 'Hochgeladen', url: 'URL' } },
  pt: { playback: { searchingDownload: '🔍 Pesquisando e baixando...', chooseTrack: 'Escolha um resultado do YouTube:', downloadingSelected: '⬇️ Baixando faixa selecionada: {title}', channel: 'Canal', views: 'Visualizações', upload: 'Enviado', url: 'URL' } },
  ar: { playback: { searchingDownload: '🔍 جارٍ البحث والتنزيل...', chooseTrack: 'اختر نتيجة من يوتيوب:', downloadingSelected: '⬇️ جارٍ تنزيل المقطع المحدد: {title}', channel: 'القناة', views: 'المشاهدات', upload: 'الرفع', url: 'الرابط' } },
  tr: { playback: { searchingDownload: '🔍 Aranıyor ve indiriliyor...', chooseTrack: 'Bir YouTube sonucu seç:', downloadingSelected: '⬇️ Seçilen parça indiriliyor: {title}', channel: 'Kanal', views: 'Görüntülenme', upload: 'Yükleme', url: 'URL' } },
  ko: { playback: { searchingDownload: '🔍 검색 및 다운로드 중...', chooseTrack: 'YouTube 결과를 선택하세요:', downloadingSelected: '⬇️ 선택한 트랙 다운로드 중: {title}', channel: '채널', views: '조회수', upload: '업로드', url: 'URL' } },
  zh: { playback: { searchingDownload: '🔍 正在搜索并下载...', chooseTrack: '请选择一个 YouTube 结果：', downloadingSelected: '⬇️ 正在下载已选择的曲目：{title}', channel: '频道', views: '观看次数', upload: '上传', url: '链接' } },
};

for (const [code, override] of Object.entries(playbackSelectionTranslations)) {
  translations[code] = mergeDeep(translations[code], override);
}

const featureTranslations = {
  id: {
    buttons: { resume: '▶️ Lanjutkan', mute: '🔇 Bisukan', unmute: '🔊 Bunyikan', addToPlaylist: '➕ Playlist', close: '✖️ Tutup' },
    callbacks: { track: 'Lagu', nowPlaying: 'Sedang Diputar', paused: 'Dijeda', muted: 'Dibisukan', noActivePlayback: 'Tidak ada pemutaran aktif.', settingsIgnored: 'Callback pengaturan ditangani terpisah.', closingPanel: 'Menutup panel.', trackSkipped: 'Lagu dilewati.', playbackStopped: 'Pemutaran dihentikan.', playbackPaused: 'Pemutaran dijeda.', playbackResumed: 'Pemutaran dilanjutkan.', playbackMuted: 'Pemutaran dibisukan.', playbackUnmuted: 'Pemutaran dibunyikan.', actionFailed: 'Tidak dapat memproses aksi pemutaran.', requestedBy: 'Diminta oleh: {user}', pausedBy: 'Dijeda oleh {user}', resumedBy: 'Dilanjutkan oleh {user}', mutedBy: 'Dibisukan oleh {user}', unmutedBy: 'Dibunyikan oleh {user}', defaultPlaylistName: 'Playlist Saya (TgMusic)', addedToPlaylist: 'Lagu "{song}" ditambahkan ke playlist "{playlist}".' },
    auth: { listTitle: 'Pengguna Terotorisasi', none: 'Tidak ada pengguna terotorisasi.', groupOnly: 'Perintah ini hanya bisa digunakan di grup.', adminOnly: 'Kamu harus menjadi administrator untuk memakai perintah ini.', adminVerifyFailed: 'Tidak dapat memverifikasi status administrator.', targetRequired: 'Balas pengguna atau berikan ID pengguna numerik.', already: 'Pengguna ini sudah diotorisasi.', notAuthorized: 'Pengguna ini belum diotorisasi.', added: 'Pengguna {userId} telah diotorisasi.', removed: 'Pengguna {userId} dihapus dari daftar otorisasi.', addFailed: 'Gagal mengotorisasi pengguna.', removeFailed: 'Gagal menghapus pengguna terotorisasi.' },
    devs: { devOnly: 'Hanya developer yang dapat menggunakan perintah ini.', noActiveChats: 'Tidak ada chat aktif ditemukan.', clearAssistantsDone: 'Menghapus assistant dari {count} chat.', clearAssistantsFailed: 'Gagal membersihkan assistant: {error}', leaveAllStarted: 'Assistant sedang keluar dari semua chat...', leaveAllDone: 'Assistant keluar dari {count} chat.', leaveAllFailed: 'Gagal keluar dari semua chat: {error}', loggerMissing: 'Harap atur LOGGER_ID di .env terlebih dahulu.', loggerUsage: 'Penggunaan: /logger [enable|disable|on|off]\nStatus saat ini: {status}', loggerEnabled: 'Logger diaktifkan', loggerDisabled: 'Logger dinonaktifkan', loggerInvalid: "Argumen tidak valid. Gunakan 'enable', 'disable', 'on', atau 'off'." },
    broadcast: { usage: 'Balas pesan untuk broadcast.\n\nPenggunaan:\n/broadcast -chat : hanya grup\n/broadcast -user : hanya pengguna\n/broadcast -both : grup + pengguna (default)\n/broadcast -copy : kirim sebagai salinan\n\nContoh:\n/broadcast\n/broadcast -chat\n/broadcast -user -copy', started: 'Broadcast dimulai.', ended: 'Broadcast selesai.\nGrup: {groups}\nPengguna: {users}', stopped: 'Broadcast dihentikan.\nGrup: {groups}\nPengguna: {users}', stopRequested: 'Broadcast dihentikan.', noneInProgress: 'Tidak ada broadcast berjalan.', alreadyInProgress: 'Broadcast sedang berjalan.', noTargets: 'Tidak ada target ditemukan.', failed: 'Broadcast gagal: {error}' },
  },
  ru: {
    buttons: { resume: '▶️ Продолжить', mute: '🔇 Выкл. звук', unmute: '🔊 Вкл. звук', addToPlaylist: '➕ Плейлист', close: '✖️ Закрыть' },
    callbacks: { track: 'Трек', nowPlaying: 'Сейчас играет', paused: 'На паузе', muted: 'Без звука', noActivePlayback: 'Активного воспроизведения нет.', settingsIgnored: 'Кнопки настроек обрабатываются отдельно.', closingPanel: 'Закрываю панель.', trackSkipped: 'Трек пропущен.', playbackStopped: 'Воспроизведение остановлено.', playbackPaused: 'Воспроизведение на паузе.', playbackResumed: 'Воспроизведение продолжено.', playbackMuted: 'Звук выключен.', playbackUnmuted: 'Звук включен.', actionFailed: 'Не удалось выполнить действие.', requestedBy: 'Запросил: {user}', pausedBy: 'Поставил на паузу: {user}', resumedBy: 'Продолжил: {user}', mutedBy: 'Выключил звук: {user}', unmutedBy: 'Включил звук: {user}', defaultPlaylistName: 'Мой плейлист (TgMusic)', addedToPlaylist: 'Трек "{song}" добавлен в плейлист "{playlist}".' },
    auth: { listTitle: 'Авторизованные пользователи', none: 'Авторизованных пользователей нет.', groupOnly: 'Эту команду можно использовать только в группах.', adminOnly: 'Для этой команды нужны права администратора.', adminVerifyFailed: 'Не удалось проверить статус администратора.', targetRequired: 'Ответьте пользователю или укажите числовой ID.', already: 'Этот пользователь уже авторизован.', notAuthorized: 'Этот пользователь не авторизован.', added: 'Пользователь {userId} авторизован.', removed: 'Пользователь {userId} удалён из списка авторизации.', addFailed: 'Не удалось авторизовать пользователя.', removeFailed: 'Не удалось удалить авторизованного пользователя.' },
    broadcast: { usage: 'Ответьте на сообщение для рассылки.\n\nИспользование:\n/broadcast -chat : только группы\n/broadcast -user : только пользователи\n/broadcast -both : группы + пользователи (по умолчанию)\n/broadcast -copy : отправить копией', started: 'Рассылка началась.', ended: 'Рассылка завершена.\nГруппы: {groups}\nПользователи: {users}', stopped: 'Рассылка остановлена.\nГруппы: {groups}\nПользователи: {users}', stopRequested: 'Рассылка остановлена.', noneInProgress: 'Активной рассылки нет.', alreadyInProgress: 'Рассылка уже выполняется.', noTargets: 'Цели не найдены.', failed: 'Ошибка рассылки: {error}' },
  },
  ja: {
    buttons: { resume: '▶️ 再開', mute: '🔇 ミュート', unmute: '🔊 ミュート解除', addToPlaylist: '➕ プレイリスト', close: '✖️ 閉じる' },
    callbacks: { track: '曲', nowPlaying: '再生中', paused: '一時停止中', muted: 'ミュート中', noActivePlayback: '再生中のものはありません。', settingsIgnored: '設定コールバックは別に処理されます。', closingPanel: 'パネルを閉じます。', trackSkipped: '曲をスキップしました。', playbackStopped: '再生を停止しました。', playbackPaused: '再生を一時停止しました。', playbackResumed: '再生を再開しました。', playbackMuted: '再生をミュートしました。', playbackUnmuted: 'ミュートを解除しました。', actionFailed: '再生操作を処理できませんでした。', requestedBy: 'リクエスト: {user}', pausedBy: '{user} が一時停止しました', resumedBy: '{user} が再開しました', mutedBy: '{user} がミュートしました', unmutedBy: '{user} がミュート解除しました', defaultPlaylistName: 'マイプレイリスト (TgMusic)', addedToPlaylist: '曲「{song}」をプレイリスト「{playlist}」に追加しました。' },
    auth: { listTitle: '認証済みユーザー', none: '認証済みユーザーはいません。', groupOnly: 'このコマンドはグループでのみ使用できます。', adminOnly: 'このコマンドには管理者権限が必要です。', adminVerifyFailed: '管理者状態を確認できません。', targetRequired: 'ユーザーに返信するか数値のユーザーIDを指定してください。', already: 'このユーザーは既に認証済みです。', notAuthorized: 'このユーザーは認証されていません。', added: 'ユーザー {userId} を認証しました。', removed: 'ユーザー {userId} を認証リストから削除しました。', addFailed: 'ユーザーの認証に失敗しました。', removeFailed: '認証済みユーザーの削除に失敗しました。' },
    broadcast: { usage: '配信するメッセージに返信してください。\n\n使い方:\n/broadcast -chat : グループのみ\n/broadcast -user : ユーザーのみ\n/broadcast -both : グループ + ユーザー (既定)\n/broadcast -copy : コピーとして送信', started: '一斉配信を開始しました。', ended: '一斉配信が完了しました。\nグループ: {groups}\nユーザー: {users}', stopped: '一斉配信を停止しました。\nグループ: {groups}\nユーザー: {users}', stopRequested: '一斉配信を停止しました。', noneInProgress: '実行中の一斉配信はありません。', alreadyInProgress: '一斉配信は既に実行中です。', noTargets: '送信先が見つかりません。', failed: '一斉配信に失敗しました: {error}' },
  },
  hi: {
    buttons: { resume: '▶️ फिर शुरू', mute: '🔇 म्यूट', unmute: '🔊 अनम्यूट', addToPlaylist: '➕ प्लेलिस्ट', close: '✖️ बंद' },
    callbacks: { track: 'ट्रैक', nowPlaying: 'अभी चल रहा है', paused: 'रुका हुआ', muted: 'म्यूट', noActivePlayback: 'कोई सक्रिय प्लेबैक नहीं है।', settingsIgnored: 'सेटिंग callback अलग से संभाले जाते हैं।', closingPanel: 'पैनल बंद हो रहा है।', trackSkipped: 'ट्रैक छोड़ दिया गया।', playbackStopped: 'प्लेबैक रोक दिया गया।', playbackPaused: 'प्लेबैक रोक दिया गया।', playbackResumed: 'प्लेबैक फिर शुरू हुआ।', playbackMuted: 'प्लेबैक म्यूट हुआ।', playbackUnmuted: 'प्लेबैक अनम्यूट हुआ।', actionFailed: 'प्लेबैक कार्रवाई प्रोसेस नहीं हो सकी।', requestedBy: 'अनुरोधकर्ता: {user}', pausedBy: '{user} ने रोका', resumedBy: '{user} ने शुरू किया', mutedBy: '{user} ने म्यूट किया', unmutedBy: '{user} ने अनम्यूट किया', defaultPlaylistName: 'मेरी प्लेलिस्ट (TgMusic)', addedToPlaylist: 'ट्रैक "{song}" प्लेलिस्ट "{playlist}" में जोड़ा गया।' },
    auth: { listTitle: 'अधिकृत उपयोगकर्ता', none: 'कोई अधिकृत उपयोगकर्ता नहीं मिला।', groupOnly: 'यह कमांड केवल ग्रुप में इस्तेमाल हो सकता है।', adminOnly: 'इस कमांड के लिए admin होना जरूरी है।', adminVerifyFailed: 'Admin स्थिति सत्यापित नहीं हो सकी।', targetRequired: 'किसी user को reply करें या numeric user ID दें।', already: 'यह user पहले से authorized है।', notAuthorized: 'यह user authorized नहीं है।', added: 'User {userId} authorized हो गया।', removed: 'User {userId} authorization list से हटाया गया।', addFailed: 'User को authorize करने में विफल।', removeFailed: 'Authorized user हटाने में विफल।' },
    broadcast: { usage: 'Broadcast के लिए किसी message पर reply करें।\n\nUsage:\n/broadcast -chat : केवल groups\n/broadcast -user : केवल users\n/broadcast -both : groups + users (default)\n/broadcast -copy : copy के रूप में भेजें', started: 'Broadcast शुरू हुआ।', ended: 'Broadcast समाप्त।\nGroups: {groups}\nUsers: {users}', stopped: 'Broadcast रोका गया।\nGroups: {groups}\nUsers: {users}', stopRequested: 'Broadcast रोका गया।', noneInProgress: 'कोई broadcast चल नहीं रहा है।', alreadyInProgress: 'Broadcast पहले से चल रहा है।', noTargets: 'कोई target नहीं मिला।', failed: 'Broadcast विफल: {error}' },
  },
  it: {
    buttons: { resume: '▶️ Riprendi', mute: '🔇 Muta', unmute: '🔊 Riattiva', addToPlaylist: '➕ Playlist', close: '✖️ Chiudi' },
    callbacks: { track: 'Traccia', nowPlaying: 'In riproduzione', paused: 'In pausa', muted: 'Muto', noActivePlayback: 'Non c’è una riproduzione attiva.', settingsIgnored: 'I callback delle impostazioni sono gestiti separatamente.', closingPanel: 'Chiudo il pannello.', trackSkipped: 'Traccia saltata.', playbackStopped: 'Riproduzione fermata.', playbackPaused: 'Riproduzione in pausa.', playbackResumed: 'Riproduzione ripresa.', playbackMuted: 'Riproduzione mutata.', playbackUnmuted: 'Audio riattivato.', actionFailed: 'Impossibile eseguire l’azione di riproduzione.', requestedBy: 'Richiesto da: {user}', pausedBy: 'Messo in pausa da {user}', resumedBy: 'Ripreso da {user}', mutedBy: 'Mutato da {user}', unmutedBy: 'Riattivato da {user}', defaultPlaylistName: 'La mia playlist (TgMusic)', addedToPlaylist: 'Traccia "{song}" aggiunta alla playlist "{playlist}".' },
    auth: { listTitle: 'Utenti autorizzati', none: 'Nessun utente autorizzato trovato.', groupOnly: 'Questo comando può essere usato solo nei gruppi.', adminOnly: 'Devi essere amministratore per usare questo comando.', adminVerifyFailed: 'Impossibile verificare lo stato di amministratore.', targetRequired: 'Rispondi a un utente o fornisci un ID utente numerico.', already: 'Questo utente è già autorizzato.', notAuthorized: 'Questo utente non è autorizzato.', added: 'Utente {userId} autorizzato.', removed: 'Utente {userId} rimosso dalla lista autorizzati.', addFailed: 'Impossibile autorizzare l’utente.', removeFailed: 'Impossibile rimuovere l’utente autorizzato.' },
    broadcast: { usage: 'Rispondi a un messaggio da trasmettere.\n\nUso:\n/broadcast -chat : solo gruppi\n/broadcast -user : solo utenti\n/broadcast -both : gruppi + utenti (default)\n/broadcast -copy : invia come copia', started: 'Broadcast avviato.', ended: 'Broadcast terminato.\nGruppi: {groups}\nUtenti: {users}', stopped: 'Broadcast fermato.\nGruppi: {groups}\nUtenti: {users}', stopRequested: 'Broadcast fermato.', noneInProgress: 'Nessun broadcast in corso.', alreadyInProgress: 'Un broadcast è già in corso.', noTargets: 'Nessun destinatario trovato.', failed: 'Broadcast fallito: {error}' },
  },
  es: {
    buttons: { resume: '▶️ Reanudar', mute: '🔇 Silenciar', unmute: '🔊 Activar sonido', addToPlaylist: '➕ Playlist', close: '✖️ Cerrar' },
    callbacks: { track: 'Pista', nowPlaying: 'Reproduciendo', paused: 'Pausado', muted: 'Silenciado', noActivePlayback: 'No hay reproducción activa.', settingsIgnored: 'Los callbacks de ajustes se manejan por separado.', closingPanel: 'Cerrando panel.', trackSkipped: 'Pista saltada.', playbackStopped: 'Reproducción detenida.', playbackPaused: 'Reproducción pausada.', playbackResumed: 'Reproducción reanudada.', playbackMuted: 'Reproducción silenciada.', playbackUnmuted: 'Sonido reactivado.', actionFailed: 'No se pudo procesar la acción de reproducción.', requestedBy: 'Pedido por: {user}', pausedBy: 'Pausado por {user}', resumedBy: 'Reanudado por {user}', mutedBy: 'Silenciado por {user}', unmutedBy: 'Sonido activado por {user}', defaultPlaylistName: 'Mi playlist (TgMusic)', addedToPlaylist: 'Pista "{song}" añadida a la playlist "{playlist}".' },
    auth: { listTitle: 'Usuarios autorizados', none: 'No se encontraron usuarios autorizados.', groupOnly: 'Este comando solo se puede usar en grupos.', adminOnly: 'Debes ser administrador para usar este comando.', adminVerifyFailed: 'No se pudo verificar el estado de administrador.', targetRequired: 'Responde a un usuario o proporciona un ID numérico.', already: 'Este usuario ya está autorizado.', notAuthorized: 'Este usuario no está autorizado.', added: 'Usuario {userId} autorizado.', removed: 'Usuario {userId} eliminado de la lista autorizada.', addFailed: 'No se pudo autorizar al usuario.', removeFailed: 'No se pudo eliminar al usuario autorizado.' },
    broadcast: { usage: 'Responde a un mensaje para difundirlo.\n\nUso:\n/broadcast -chat : solo grupos\n/broadcast -user : solo usuarios\n/broadcast -both : grupos + usuarios (default)\n/broadcast -copy : enviar como copia', started: 'Broadcast iniciado.', ended: 'Broadcast finalizado.\nGrupos: {groups}\nUsuarios: {users}', stopped: 'Broadcast detenido.\nGrupos: {groups}\nUsuarios: {users}', stopRequested: 'Broadcast detenido.', noneInProgress: 'No hay broadcast en curso.', alreadyInProgress: 'Ya hay un broadcast en curso.', noTargets: 'No se encontraron destinatarios.', failed: 'Broadcast fallido: {error}' },
  },
  fr: {
    buttons: { resume: '▶️ Reprendre', mute: '🔇 Muet', unmute: '🔊 Réactiver', addToPlaylist: '➕ Playlist', close: '✖️ Fermer' },
    callbacks: { track: 'Piste', nowPlaying: 'En lecture', paused: 'En pause', muted: 'Muet', noActivePlayback: 'Aucune lecture active.', settingsIgnored: 'Les callbacks des paramètres sont gérés séparément.', closingPanel: 'Fermeture du panneau.', trackSkipped: 'Piste passée.', playbackStopped: 'Lecture arrêtée.', playbackPaused: 'Lecture mise en pause.', playbackResumed: 'Lecture reprise.', playbackMuted: 'Lecture mise en sourdine.', playbackUnmuted: 'Son réactivé.', actionFailed: 'Impossible de traiter l’action de lecture.', requestedBy: 'Demandé par : {user}', pausedBy: 'Mis en pause par {user}', resumedBy: 'Repris par {user}', mutedBy: 'Mis en sourdine par {user}', unmutedBy: 'Réactivé par {user}', defaultPlaylistName: 'Ma playlist (TgMusic)', addedToPlaylist: 'Piste "{song}" ajoutée à la playlist "{playlist}".' },
    auth: { listTitle: 'Utilisateurs autorisés', none: 'Aucun utilisateur autorisé trouvé.', groupOnly: 'Cette commande ne peut être utilisée que dans les groupes.', adminOnly: 'Vous devez être administrateur pour utiliser cette commande.', adminVerifyFailed: 'Impossible de vérifier le statut administrateur.', targetRequired: 'Répondez à un utilisateur ou fournissez un ID numérique.', already: 'Cet utilisateur est déjà autorisé.', notAuthorized: 'Cet utilisateur n’est pas autorisé.', added: 'Utilisateur {userId} autorisé.', removed: 'Utilisateur {userId} retiré de la liste autorisée.', addFailed: 'Impossible d’autoriser l’utilisateur.', removeFailed: 'Impossible de retirer l’utilisateur autorisé.' },
    broadcast: { usage: 'Répondez à un message pour le diffuser.\n\nUtilisation :\n/broadcast -chat : groupes uniquement\n/broadcast -user : utilisateurs uniquement\n/broadcast -both : groupes + utilisateurs (défaut)\n/broadcast -copy : envoyer comme copie', started: 'Diffusion commencée.', ended: 'Diffusion terminée.\nGroupes : {groups}\nUtilisateurs : {users}', stopped: 'Diffusion arrêtée.\nGroupes : {groups}\nUtilisateurs : {users}', stopRequested: 'Diffusion arrêtée.', noneInProgress: 'Aucune diffusion en cours.', alreadyInProgress: 'Une diffusion est déjà en cours.', noTargets: 'Aucune cible trouvée.', failed: 'Échec de la diffusion : {error}' },
  },
  de: {
    buttons: { resume: '▶️ Fortsetzen', mute: '🔇 Stumm', unmute: '🔊 Ton an', addToPlaylist: '➕ Playlist', close: '✖️ Schließen' },
    callbacks: { track: 'Titel', nowPlaying: 'Läuft gerade', paused: 'Pausiert', muted: 'Stumm', noActivePlayback: 'Keine aktive Wiedergabe.', settingsIgnored: 'Einstellungs-Callbacks werden separat behandelt.', closingPanel: 'Panel wird geschlossen.', trackSkipped: 'Titel übersprungen.', playbackStopped: 'Wiedergabe gestoppt.', playbackPaused: 'Wiedergabe pausiert.', playbackResumed: 'Wiedergabe fortgesetzt.', playbackMuted: 'Wiedergabe stummgeschaltet.', playbackUnmuted: 'Ton wieder aktiviert.', actionFailed: 'Wiedergabeaktion konnte nicht verarbeitet werden.', requestedBy: 'Angefordert von: {user}', pausedBy: 'Pausiert von {user}', resumedBy: 'Fortgesetzt von {user}', mutedBy: 'Stummgeschaltet von {user}', unmutedBy: 'Ton aktiviert von {user}', defaultPlaylistName: 'Meine Playlist (TgMusic)', addedToPlaylist: 'Titel "{song}" zur Playlist "{playlist}" hinzugefügt.' },
    auth: { listTitle: 'Autorisierte Benutzer', none: 'Keine autorisierten Benutzer gefunden.', groupOnly: 'Dieser Befehl kann nur in Gruppen verwendet werden.', adminOnly: 'Du musst Administrator sein, um diesen Befehl zu verwenden.', adminVerifyFailed: 'Administratorstatus konnte nicht geprüft werden.', targetRequired: 'Antworte einem Benutzer oder gib eine numerische Benutzer-ID an.', already: 'Dieser Benutzer ist bereits autorisiert.', notAuthorized: 'Dieser Benutzer ist nicht autorisiert.', added: 'Benutzer {userId} wurde autorisiert.', removed: 'Benutzer {userId} wurde aus der Autorisierungsliste entfernt.', addFailed: 'Benutzer konnte nicht autorisiert werden.', removeFailed: 'Autorisierter Benutzer konnte nicht entfernt werden.' },
    broadcast: { usage: 'Antworte auf eine Nachricht, um sie zu senden.\n\nNutzung:\n/broadcast -chat : nur Gruppen\n/broadcast -user : nur Benutzer\n/broadcast -both : Gruppen + Benutzer (Standard)\n/broadcast -copy : als Kopie senden', started: 'Broadcast gestartet.', ended: 'Broadcast beendet.\nGruppen: {groups}\nBenutzer: {users}', stopped: 'Broadcast gestoppt.\nGruppen: {groups}\nBenutzer: {users}', stopRequested: 'Broadcast gestoppt.', noneInProgress: 'Kein Broadcast läuft.', alreadyInProgress: 'Ein Broadcast läuft bereits.', noTargets: 'Keine Ziele gefunden.', failed: 'Broadcast fehlgeschlagen: {error}' },
  },
  pt: {
    buttons: { resume: '▶️ Retomar', mute: '🔇 Silenciar', unmute: '🔊 Reativar', addToPlaylist: '➕ Playlist', close: '✖️ Fechar' },
    callbacks: { track: 'Faixa', nowPlaying: 'Tocando agora', paused: 'Pausado', muted: 'Silenciado', noActivePlayback: 'Não há reprodução ativa.', settingsIgnored: 'Callbacks de configurações são tratados separadamente.', closingPanel: 'Fechando painel.', trackSkipped: 'Faixa pulada.', playbackStopped: 'Reprodução parada.', playbackPaused: 'Reprodução pausada.', playbackResumed: 'Reprodução retomada.', playbackMuted: 'Reprodução silenciada.', playbackUnmuted: 'Som reativado.', actionFailed: 'Não foi possível processar a ação de reprodução.', requestedBy: 'Pedido por: {user}', pausedBy: 'Pausado por {user}', resumedBy: 'Retomado por {user}', mutedBy: 'Silenciado por {user}', unmutedBy: 'Reativado por {user}', defaultPlaylistName: 'Minha playlist (TgMusic)', addedToPlaylist: 'Faixa "{song}" adicionada à playlist "{playlist}".' },
    auth: { listTitle: 'Usuários autorizados', none: 'Nenhum usuário autorizado encontrado.', groupOnly: 'Este comando só pode ser usado em grupos.', adminOnly: 'Você precisa ser administrador para usar este comando.', adminVerifyFailed: 'Não foi possível verificar o status de administrador.', targetRequired: 'Responda a um usuário ou forneça um ID numérico.', already: 'Este usuário já está autorizado.', notAuthorized: 'Este usuário não está autorizado.', added: 'Usuário {userId} autorizado.', removed: 'Usuário {userId} removido da lista autorizada.', addFailed: 'Falha ao autorizar o usuário.', removeFailed: 'Falha ao remover usuário autorizado.' },
    broadcast: { usage: 'Responda a uma mensagem para transmitir.\n\nUso:\n/broadcast -chat : apenas grupos\n/broadcast -user : apenas usuários\n/broadcast -both : grupos + usuários (padrão)\n/broadcast -copy : enviar como cópia', started: 'Broadcast iniciado.', ended: 'Broadcast finalizado.\nGrupos: {groups}\nUsuários: {users}', stopped: 'Broadcast parado.\nGrupos: {groups}\nUsuários: {users}', stopRequested: 'Broadcast parado.', noneInProgress: 'Nenhum broadcast em andamento.', alreadyInProgress: 'Já há um broadcast em andamento.', noTargets: 'Nenhum destino encontrado.', failed: 'Broadcast falhou: {error}' },
  },
  ar: {
    buttons: { resume: '▶️ استئناف', mute: '🔇 كتم', unmute: '🔊 إلغاء الكتم', addToPlaylist: '➕ قائمة', close: '✖️ إغلاق' },
    callbacks: { track: 'المقطع', nowPlaying: 'قيد التشغيل', paused: 'متوقف مؤقتًا', muted: 'مكتوم', noActivePlayback: 'لا يوجد تشغيل نشط.', settingsIgnored: 'يتم التعامل مع أزرار الإعدادات بشكل منفصل.', closingPanel: 'جارٍ إغلاق اللوحة.', trackSkipped: 'تم تخطي المقطع.', playbackStopped: 'تم إيقاف التشغيل.', playbackPaused: 'تم إيقاف التشغيل مؤقتًا.', playbackResumed: 'تم استئناف التشغيل.', playbackMuted: 'تم كتم التشغيل.', playbackUnmuted: 'تم إلغاء كتم التشغيل.', actionFailed: 'تعذرت معالجة إجراء التشغيل.', requestedBy: 'طلب بواسطة: {user}', pausedBy: 'أوقفه مؤقتًا {user}', resumedBy: 'استأنفه {user}', mutedBy: 'كتمه {user}', unmutedBy: 'ألغى كتمه {user}', defaultPlaylistName: 'قائمتي (TgMusic)', addedToPlaylist: 'تمت إضافة المقطع "{song}" إلى القائمة "{playlist}".' },
    auth: { listTitle: 'المستخدمون المصرح لهم', none: 'لم يتم العثور على مستخدمين مصرح لهم.', groupOnly: 'لا يمكن استخدام هذا الأمر إلا في المجموعات.', adminOnly: 'يجب أن تكون مشرفًا لاستخدام هذا الأمر.', adminVerifyFailed: 'تعذر التحقق من حالة المشرف.', targetRequired: 'قم بالرد على مستخدم أو قدم معرف مستخدم رقمي.', already: 'هذا المستخدم مصرح له بالفعل.', notAuthorized: 'هذا المستخدم غير مصرح له.', added: 'تم التصريح للمستخدم {userId}.', removed: 'تمت إزالة المستخدم {userId} من قائمة التصريح.', addFailed: 'فشل التصريح للمستخدم.', removeFailed: 'فشلت إزالة المستخدم المصرح له.' },
    broadcast: { usage: 'قم بالرد على رسالة لبثها.\n\nالاستخدام:\n/broadcast -chat : المجموعات فقط\n/broadcast -user : المستخدمون فقط\n/broadcast -both : المجموعات + المستخدمون (افتراضي)\n/broadcast -copy : إرسال كنسخة', started: 'بدأ البث.', ended: 'انتهى البث.\nالمجموعات: {groups}\nالمستخدمون: {users}', stopped: 'تم إيقاف البث.\nالمجموعات: {groups}\nالمستخدمون: {users}', stopRequested: 'تم إيقاف البث.', noneInProgress: 'لا يوجد بث قيد التشغيل.', alreadyInProgress: 'يوجد بث قيد التشغيل بالفعل.', noTargets: 'لم يتم العثور على أهداف.', failed: 'فشل البث: {error}' },
  },
  tr: {
    buttons: { resume: '▶️ Sürdür', mute: '🔇 Sustur', unmute: '🔊 Sesi aç', addToPlaylist: '➕ Playlist', close: '✖️ Kapat' },
    callbacks: { track: 'Parça', nowPlaying: 'Çalıyor', paused: 'Duraklatıldı', muted: 'Sessiz', noActivePlayback: 'Aktif oynatma yok.', settingsIgnored: 'Ayar callbackleri ayrı işlenir.', closingPanel: 'Panel kapatılıyor.', trackSkipped: 'Parça atlandı.', playbackStopped: 'Oynatma durduruldu.', playbackPaused: 'Oynatma duraklatıldı.', playbackResumed: 'Oynatma sürdürüldü.', playbackMuted: 'Oynatma susturuldu.', playbackUnmuted: 'Ses açıldı.', actionFailed: 'Oynatma eylemi işlenemedi.', requestedBy: 'İsteyen: {user}', pausedBy: '{user} duraklattı', resumedBy: '{user} sürdürdü', mutedBy: '{user} susturdu', unmutedBy: '{user} sesi açtı', defaultPlaylistName: 'Playlistim (TgMusic)', addedToPlaylist: '"{song}" parçası "{playlist}" playlistine eklendi.' },
    auth: { listTitle: 'Yetkili kullanıcılar', none: 'Yetkili kullanıcı bulunamadı.', groupOnly: 'Bu komut sadece gruplarda kullanılabilir.', adminOnly: 'Bu komutu kullanmak için yönetici olmalısın.', adminVerifyFailed: 'Yönetici durumu doğrulanamadı.', targetRequired: 'Bir kullanıcıya yanıt ver veya sayısal kullanıcı ID gir.', already: 'Bu kullanıcı zaten yetkili.', notAuthorized: 'Bu kullanıcı yetkili değil.', added: '{userId} kullanıcısı yetkilendirildi.', removed: '{userId} kullanıcısı yetki listesinden kaldırıldı.', addFailed: 'Kullanıcı yetkilendirilemedi.', removeFailed: 'Yetkili kullanıcı kaldırılamadı.' },
    broadcast: { usage: 'Yayınlamak için bir mesaja yanıt ver.\n\nKullanım:\n/broadcast -chat : sadece gruplar\n/broadcast -user : sadece kullanıcılar\n/broadcast -both : gruplar + kullanıcılar (varsayılan)\n/broadcast -copy : kopya olarak gönder', started: 'Broadcast başladı.', ended: 'Broadcast bitti.\nGruplar: {groups}\nKullanıcılar: {users}', stopped: 'Broadcast durduruldu.\nGruplar: {groups}\nKullanıcılar: {users}', stopRequested: 'Broadcast durduruldu.', noneInProgress: 'Devam eden broadcast yok.', alreadyInProgress: 'Zaten devam eden bir broadcast var.', noTargets: 'Hedef bulunamadı.', failed: 'Broadcast başarısız: {error}' },
  },
  ko: {
    buttons: { resume: '▶️ 재개', mute: '🔇 음소거', unmute: '🔊 음소거 해제', addToPlaylist: '➕ 플레이리스트', close: '✖️ 닫기' },
    callbacks: { track: '트랙', nowPlaying: '재생 중', paused: '일시정지됨', muted: '음소거됨', noActivePlayback: '활성 재생이 없습니다.', settingsIgnored: '설정 콜백은 별도로 처리됩니다.', closingPanel: '패널을 닫습니다.', trackSkipped: '트랙을 건너뛰었습니다.', playbackStopped: '재생을 중지했습니다.', playbackPaused: '재생을 일시정지했습니다.', playbackResumed: '재생을 재개했습니다.', playbackMuted: '재생을 음소거했습니다.', playbackUnmuted: '음소거를 해제했습니다.', actionFailed: '재생 작업을 처리할 수 없습니다.', requestedBy: '요청자: {user}', pausedBy: '{user}님이 일시정지함', resumedBy: '{user}님이 재개함', mutedBy: '{user}님이 음소거함', unmutedBy: '{user}님이 음소거 해제함', defaultPlaylistName: '내 플레이리스트 (TgMusic)', addedToPlaylist: '트랙 "{song}"을(를) 플레이리스트 "{playlist}"에 추가했습니다.' },
    auth: { listTitle: '인증된 사용자', none: '인증된 사용자가 없습니다.', groupOnly: '이 명령은 그룹에서만 사용할 수 있습니다.', adminOnly: '이 명령을 사용하려면 관리자여야 합니다.', adminVerifyFailed: '관리자 상태를 확인할 수 없습니다.', targetRequired: '사용자에게 답장하거나 숫자 사용자 ID를 입력하세요.', already: '이 사용자는 이미 인증되었습니다.', notAuthorized: '이 사용자는 인증되지 않았습니다.', added: '사용자 {userId} 인증 완료.', removed: '사용자 {userId}을(를) 인증 목록에서 제거했습니다.', addFailed: '사용자 인증에 실패했습니다.', removeFailed: '인증된 사용자 제거에 실패했습니다.' },
    broadcast: { usage: '방송할 메시지에 답장하세요.\n\n사용법:\n/broadcast -chat : 그룹만\n/broadcast -user : 사용자만\n/broadcast -both : 그룹 + 사용자 (기본)\n/broadcast -copy : 복사본으로 전송', started: '방송을 시작했습니다.', ended: '방송이 종료되었습니다.\n그룹: {groups}\n사용자: {users}', stopped: '방송이 중지되었습니다.\n그룹: {groups}\n사용자: {users}', stopRequested: '방송이 중지되었습니다.', noneInProgress: '진행 중인 방송이 없습니다.', alreadyInProgress: '이미 방송이 진행 중입니다.', noTargets: '대상을 찾을 수 없습니다.', failed: '방송 실패: {error}' },
  },
  zh: {
    buttons: { resume: '▶️ 继续', mute: '🔇 静音', unmute: '🔊 取消静音', addToPlaylist: '➕ 播放列表', close: '✖️ 关闭' },
    callbacks: { track: '曲目', nowPlaying: '正在播放', paused: '已暂停', muted: '已静音', noActivePlayback: '当前没有播放。', settingsIgnored: '设置回调会单独处理。', closingPanel: '正在关闭面板。', trackSkipped: '已跳过曲目。', playbackStopped: '播放已停止。', playbackPaused: '播放已暂停。', playbackResumed: '播放已继续。', playbackMuted: '播放已静音。', playbackUnmuted: '已取消静音。', actionFailed: '无法处理播放操作。', requestedBy: '请求者：{user}', pausedBy: '{user} 已暂停', resumedBy: '{user} 已继续', mutedBy: '{user} 已静音', unmutedBy: '{user} 已取消静音', defaultPlaylistName: '我的播放列表 (TgMusic)', addedToPlaylist: '曲目“{song}”已添加到播放列表“{playlist}”。' },
    auth: { listTitle: '已授权用户', none: '未找到已授权用户。', groupOnly: '此命令只能在群组中使用。', adminOnly: '你必须是管理员才能使用此命令。', adminVerifyFailed: '无法验证管理员状态。', targetRequired: '请回复用户或提供数字用户 ID。', already: '此用户已被授权。', notAuthorized: '此用户未被授权。', added: '用户 {userId} 已授权。', removed: '用户 {userId} 已从授权列表移除。', addFailed: '授权用户失败。', removeFailed: '移除已授权用户失败。' },
    broadcast: { usage: '请回复一条消息进行广播。\n\n用法：\n/broadcast -chat : 仅群组\n/broadcast -user : 仅用户\n/broadcast -both : 群组 + 用户（默认）\n/broadcast -copy : 作为副本发送', started: '广播已开始。', ended: '广播已结束。\n群组：{groups}\n用户：{users}', stopped: '广播已停止。\n群组：{groups}\n用户：{users}', stopRequested: '广播已停止。', noneInProgress: '没有正在进行的广播。', alreadyInProgress: '已有广播正在进行。', noTargets: '未找到目标。', failed: '广播失败：{error}' },
  },
};

for (const [code, override] of Object.entries(featureTranslations)) {
  translations[code] = mergeDeep(translations[code], override);
}

const devTranslations = {
  ru: { devs: { devOnly: 'Только разработчики могут использовать эту команду.', noActiveChats: 'Активные чаты не найдены.', clearAssistantsDone: 'Ассистент удалён из {count} чатов.', clearAssistantsFailed: 'Не удалось очистить ассистентов: {error}', leaveAllStarted: 'Ассистент выходит из всех чатов...', leaveAllDone: 'Ассистент вышел из {count} чатов.', leaveAllFailed: 'Не удалось выйти из всех чатов: {error}', loggerMissing: 'Сначала задайте LOGGER_ID в .env.', loggerUsage: 'Использование: /logger [enable|disable|on|off]\nТекущий статус: {status}', loggerEnabled: 'Логгер включён', loggerDisabled: 'Логгер выключен', loggerInvalid: "Недопустимый аргумент. Используйте 'enable', 'disable', 'on' или 'off'." } },
  ja: { devs: { devOnly: 'このコマンドは開発者のみ使用できます。', noActiveChats: 'アクティブなチャットは見つかりません。', clearAssistantsDone: '{count} 件のチャットからアシスタントを削除しました。', clearAssistantsFailed: 'アシスタントのクリアに失敗しました: {error}', leaveAllStarted: 'アシスタントがすべてのチャットから退出しています...', leaveAllDone: 'アシスタントは {count} 件のチャットから退出しました。', leaveAllFailed: 'すべてのチャットから退出できませんでした: {error}', loggerMissing: '先に .env に LOGGER_ID を設定してください。', loggerUsage: '使い方: /logger [enable|disable|on|off]\n現在の状態: {status}', loggerEnabled: 'ロガーを有効にしました', loggerDisabled: 'ロガーを無効にしました', loggerInvalid: "無効な引数です。'enable'、'disable'、'on'、'off' を使ってください。" } },
  hi: { devs: { devOnly: 'यह command केवल developers के लिए है।', noActiveChats: 'कोई active chat नहीं मिला।', clearAssistantsDone: '{count} chats से assistant हटाया गया।', clearAssistantsFailed: 'Assistants साफ़ करने में विफल: {error}', leaveAllStarted: 'Assistant सभी chats छोड़ रहा है...', leaveAllDone: 'Assistant ने {count} chats छोड़े।', leaveAllFailed: 'सभी chats छोड़ने में विफल: {error}', loggerMissing: 'पहले .env में LOGGER_ID सेट करें।', loggerUsage: 'Usage: /logger [enable|disable|on|off]\nCurrent status: {status}', loggerEnabled: 'Logger enabled', loggerDisabled: 'Logger disabled', loggerInvalid: "Invalid argument. 'enable', 'disable', 'on', या 'off' इस्तेमाल करें।" } },
  it: { devs: { devOnly: 'Solo gli sviluppatori possono usare questo comando.', noActiveChats: 'Nessuna chat attiva trovata.', clearAssistantsDone: 'Assistente rimosso da {count} chat.', clearAssistantsFailed: 'Impossibile pulire gli assistenti: {error}', leaveAllStarted: 'L’assistente sta lasciando tutte le chat...', leaveAllDone: 'L’assistente ha lasciato {count} chat.', leaveAllFailed: 'Impossibile lasciare tutte le chat: {error}', loggerMissing: 'Imposta prima LOGGER_ID in .env.', loggerUsage: 'Uso: /logger [enable|disable|on|off]\nStato attuale: {status}', loggerEnabled: 'Logger abilitato', loggerDisabled: 'Logger disabilitato', loggerInvalid: "Argomento non valido. Usa 'enable', 'disable', 'on' o 'off'." } },
  es: { devs: { devOnly: 'Solo los desarrolladores pueden usar este comando.', noActiveChats: 'No se encontraron chats activos.', clearAssistantsDone: 'Asistente eliminado de {count} chats.', clearAssistantsFailed: 'No se pudieron limpiar los asistentes: {error}', leaveAllStarted: 'El asistente está saliendo de todos los chats...', leaveAllDone: 'El asistente salió de {count} chats.', leaveAllFailed: 'No se pudo salir de todos los chats: {error}', loggerMissing: 'Configura LOGGER_ID en .env primero.', loggerUsage: 'Uso: /logger [enable|disable|on|off]\nEstado actual: {status}', loggerEnabled: 'Logger activado', loggerDisabled: 'Logger desactivado', loggerInvalid: "Argumento inválido. Usa 'enable', 'disable', 'on' u 'off'." } },
  fr: { devs: { devOnly: 'Seuls les développeurs peuvent utiliser cette commande.', noActiveChats: 'Aucun chat actif trouvé.', clearAssistantsDone: 'Assistant retiré de {count} chats.', clearAssistantsFailed: 'Impossible de nettoyer les assistants : {error}', leaveAllStarted: 'L’assistant quitte tous les chats...', leaveAllDone: 'L’assistant a quitté {count} chats.', leaveAllFailed: 'Impossible de quitter tous les chats : {error}', loggerMissing: 'Veuillez définir LOGGER_ID dans .env d’abord.', loggerUsage: 'Utilisation : /logger [enable|disable|on|off]\nStatut actuel : {status}', loggerEnabled: 'Logger activé', loggerDisabled: 'Logger désactivé', loggerInvalid: "Argument invalide. Utilisez 'enable', 'disable', 'on' ou 'off'." } },
  de: { devs: { devOnly: 'Nur Entwickler können diesen Befehl verwenden.', noActiveChats: 'Keine aktiven Chats gefunden.', clearAssistantsDone: 'Assistent aus {count} Chats entfernt.', clearAssistantsFailed: 'Assistenten konnten nicht gelöscht werden: {error}', leaveAllStarted: 'Assistent verlässt alle Chats...', leaveAllDone: 'Assistent hat {count} Chats verlassen.', leaveAllFailed: 'Konnte nicht alle Chats verlassen: {error}', loggerMissing: 'Bitte zuerst LOGGER_ID in .env setzen.', loggerUsage: 'Nutzung: /logger [enable|disable|on|off]\nAktueller Status: {status}', loggerEnabled: 'Logger aktiviert', loggerDisabled: 'Logger deaktiviert', loggerInvalid: "Ungültiges Argument. Verwende 'enable', 'disable', 'on' oder 'off'." } },
  pt: { devs: { devOnly: 'Apenas desenvolvedores podem usar este comando.', noActiveChats: 'Nenhum chat ativo encontrado.', clearAssistantsDone: 'Assistente removido de {count} chats.', clearAssistantsFailed: 'Falha ao limpar assistentes: {error}', leaveAllStarted: 'O assistente está saindo de todos os chats...', leaveAllDone: 'O assistente saiu de {count} chats.', leaveAllFailed: 'Falha ao sair de todos os chats: {error}', loggerMissing: 'Defina LOGGER_ID no .env primeiro.', loggerUsage: 'Uso: /logger [enable|disable|on|off]\nStatus atual: {status}', loggerEnabled: 'Logger ativado', loggerDisabled: 'Logger desativado', loggerInvalid: "Argumento inválido. Use 'enable', 'disable', 'on' ou 'off'." } },
  ar: { devs: { devOnly: 'يمكن للمطورين فقط استخدام هذا الأمر.', noActiveChats: 'لم يتم العثور على محادثات نشطة.', clearAssistantsDone: 'تمت إزالة المساعد من {count} محادثات.', clearAssistantsFailed: 'فشل مسح المساعدين: {error}', leaveAllStarted: 'المساعد يغادر كل المحادثات...', leaveAllDone: 'غادر المساعد {count} محادثات.', leaveAllFailed: 'فشل مغادرة كل المحادثات: {error}', loggerMissing: 'يرجى تعيين LOGGER_ID في .env أولاً.', loggerUsage: 'الاستخدام: /logger [enable|disable|on|off]\nالحالة الحالية: {status}', loggerEnabled: 'تم تفعيل السجل', loggerDisabled: 'تم تعطيل السجل', loggerInvalid: "وسيط غير صالح. استخدم 'enable' أو 'disable' أو 'on' أو 'off'." } },
  tr: { devs: { devOnly: 'Bu komutu sadece geliştiriciler kullanabilir.', noActiveChats: 'Aktif sohbet bulunamadı.', clearAssistantsDone: 'Asistan {count} sohbetten kaldırıldı.', clearAssistantsFailed: 'Asistanlar temizlenemedi: {error}', leaveAllStarted: 'Asistan tüm sohbetlerden ayrılıyor...', leaveAllDone: 'Asistan {count} sohbetten ayrıldı.', leaveAllFailed: 'Tüm sohbetlerden ayrılma başarısız: {error}', loggerMissing: 'Önce .env içinde LOGGER_ID ayarla.', loggerUsage: 'Kullanım: /logger [enable|disable|on|off]\nMevcut durum: {status}', loggerEnabled: 'Logger etkinleştirildi', loggerDisabled: 'Logger devre dışı', loggerInvalid: "Geçersiz argüman. 'enable', 'disable', 'on' veya 'off' kullan." } },
  ko: { devs: { devOnly: '개발자만 이 명령을 사용할 수 있습니다.', noActiveChats: '활성 채팅을 찾을 수 없습니다.', clearAssistantsDone: '{count}개 채팅에서 어시스턴트를 제거했습니다.', clearAssistantsFailed: '어시스턴트 정리에 실패했습니다: {error}', leaveAllStarted: '어시스턴트가 모든 채팅에서 나가는 중...', leaveAllDone: '어시스턴트가 {count}개 채팅에서 나갔습니다.', leaveAllFailed: '모든 채팅에서 나가지 못했습니다: {error}', loggerMissing: '먼저 .env에 LOGGER_ID를 설정하세요.', loggerUsage: '사용법: /logger [enable|disable|on|off]\n현재 상태: {status}', loggerEnabled: '로거 활성화됨', loggerDisabled: '로거 비활성화됨', loggerInvalid: "잘못된 인수입니다. 'enable', 'disable', 'on', 'off' 중 하나를 사용하세요." } },
  zh: { devs: { devOnly: '只有开发者可以使用此命令。', noActiveChats: '未找到活跃聊天。', clearAssistantsDone: '已从 {count} 个聊天移除助手。', clearAssistantsFailed: '清理助手失败：{error}', leaveAllStarted: '助手正在离开所有聊天...', leaveAllDone: '助手已离开 {count} 个聊天。', leaveAllFailed: '离开所有聊天失败：{error}', loggerMissing: '请先在 .env 中设置 LOGGER_ID。', loggerUsage: '用法：/logger [enable|disable|on|off]\n当前状态：{status}', loggerEnabled: '日志已启用', loggerDisabled: '日志已禁用', loggerInvalid: "参数无效。请使用 'enable'、'disable'、'on' 或 'off'。" } },
};

for (const [code, override] of Object.entries(devTranslations)) {
  translations[code] = mergeDeep(translations[code], override);
}

const filterTranslations = {
  id: { filters: { botNotAdmin: 'Bot bukan administrator di chat ini.\nPromosikan bot dengan izin mengundang pengguna.', botAdminVerifyFailed: 'Tidak dapat memverifikasi status administrator bot.', botMissingInvite: 'Bot tidak memiliki izin mengundang pengguna.', botNotAdminReload: 'Bot bukan administrator di chat ini.\nGunakan /reload untuk menyegarkan cache admin.', adminRequired: 'Kamu harus menjadi administrator untuk menggunakan perintah ini.', notAuthorized: 'Kamu tidak diizinkan menggunakan perintah ini.', adminActionRequired: 'Kamu harus menjadi administrator untuk menggunakan aksi ini.', actionNotAuthorized: 'Kamu tidak diizinkan menggunakan aksi ini.', playModeAdminOnly: 'Play mode aktif.\nHanya administrator dan pengguna terotorisasi yang dapat memulai playback.' } },
  ru: { playback: { voiceChatInactiveWarning: '⚠️ В этом чате ещё не запущен голосовой чат. Сначала запустите голосовой/видеочат, затем включайте музыку.' }, filters: { botNotAdmin: 'Бот не администратор в этом чате.\nВыдайте боту право приглашать пользователей.', botAdminVerifyFailed: 'Не удалось проверить статус администратора бота.', botMissingInvite: 'У бота нет права приглашать пользователей.', botNotAdminReload: 'Бот не администратор в этом чате.\nИспользуйте /reload для обновления кэша админов.', adminRequired: 'Вы должны быть администратором для этой команды.', notAuthorized: 'Вы не авторизованы для этой команды.', adminActionRequired: 'Вы должны быть администратором для этого действия.', actionNotAuthorized: 'Вы не авторизованы для этого действия.', playModeAdminOnly: 'Режим play включён.\nТолько администраторы и авторизованные пользователи могут запускать воспроизведение.' } },
  ja: { playback: { voiceChatInactiveWarning: '⚠️ このグループではまだ音声チャットが開始されていません。先に音声/ビデオチャットを開始してから再生してください。' }, filters: { botNotAdmin: 'このチャットでボットは管理者ではありません。\nユーザー招待権限付きで昇格してください。', botAdminVerifyFailed: 'ボットの管理者状態を確認できません。', botMissingInvite: 'ボットにユーザー招待権限がありません。', botNotAdminReload: 'このチャットでボットは管理者ではありません。\n/reload で管理者キャッシュを更新してください。', adminRequired: 'このコマンドには管理者権限が必要です。', notAuthorized: 'このコマンドを使用する権限がありません。', adminActionRequired: 'この操作には管理者権限が必要です。', actionNotAuthorized: 'この操作を実行する権限がありません。', playModeAdminOnly: 'Play mode が有効です。\n管理者と認証済みユーザーのみ再生を開始できます。' } },
  hi: { playback: { voiceChatInactiveWarning: '⚠️ इस समूह में अभी voice chat सक्रिय नहीं है। पहले voice/video chat शुरू करें, फिर /play चलाएँ।' }, filters: { botNotAdmin: 'Bot इस chat में administrator नहीं है।\nBot को invite users permission के साथ promote करें।', botAdminVerifyFailed: 'Bot administrator status verify नहीं हो सका।', botMissingInvite: 'Bot के पास users invite करने की permission नहीं है।', botNotAdminReload: 'Bot इस chat में administrator नहीं है।\nAdmin cache refresh करने के लिए /reload इस्तेमाल करें।', adminRequired: 'इस command के लिए administrator होना जरूरी है।', notAuthorized: 'आप इस command के लिए authorized नहीं हैं।', adminActionRequired: 'इस action के लिए administrator होना जरूरी है।', actionNotAuthorized: 'आप इस action के लिए authorized नहीं हैं।', playModeAdminOnly: 'Play mode enabled है।\nकेवल administrators और authorized users playback शुरू कर सकते हैं।' } },
  it: { playback: { voiceChatInactiveWarning: '⚠️ La chat vocale non è ancora attiva in questo gruppo. Avvia prima la chat vocale/video, poi riprova con /play.' }, filters: { botNotAdmin: 'Il bot non è amministratore in questa chat.\nPromuovi il bot con il permesso di invitare utenti.', botAdminVerifyFailed: 'Impossibile verificare lo stato amministratore del bot.', botMissingInvite: 'Il bot non ha il permesso di invitare utenti.', botNotAdminReload: 'Il bot non è amministratore in questa chat.\nUsa /reload per aggiornare la cache admin.', adminRequired: 'Devi essere amministratore per usare questo comando.', notAuthorized: 'Non sei autorizzato a usare questo comando.', adminActionRequired: 'Devi essere amministratore per questa azione.', actionNotAuthorized: 'Non sei autorizzato per questa azione.', playModeAdminOnly: 'Play mode è attivo.\nSolo amministratori e utenti autorizzati possono avviare la riproduzione.' } },
  es: { playback: { voiceChatInactiveWarning: '⚠️ El chat de voz aún no está activo en este grupo. Inicia primero el chat de voz/video y luego vuelve a usar /play.' }, filters: { botNotAdmin: 'El bot no es administrador en este chat.\nPromueve al bot con permiso para invitar usuarios.', botAdminVerifyFailed: 'No se pudo verificar el estado de administrador del bot.', botMissingInvite: 'El bot no tiene permiso para invitar usuarios.', botNotAdminReload: 'El bot no es administrador en este chat.\nUsa /reload para refrescar la caché de admins.', adminRequired: 'Debes ser administrador para usar este comando.', notAuthorized: 'No estás autorizado para usar este comando.', adminActionRequired: 'Debes ser administrador para esta acción.', actionNotAuthorized: 'No estás autorizado para esta acción.', playModeAdminOnly: 'Play mode está activado.\nSolo administradores y usuarios autorizados pueden iniciar reproducción.' } },
  fr: { playback: { voiceChatInactiveWarning: '⚠️ Le chat vocal n’est pas encore actif dans ce groupe. Lancez d’abord un chat vocal/vidéo puis relancez /play.' }, filters: { botNotAdmin: 'Le bot n’est pas administrateur dans ce chat.\nPromouvez le bot avec la permission d’inviter des utilisateurs.', botAdminVerifyFailed: 'Impossible de vérifier le statut administrateur du bot.', botMissingInvite: 'Le bot n’a pas la permission d’inviter des utilisateurs.', botNotAdminReload: 'Le bot n’est pas administrateur dans ce chat.\nUtilisez /reload pour rafraîchir le cache admin.', adminRequired: 'Vous devez être administrateur pour utiliser cette commande.', notAuthorized: 'Vous n’êtes pas autorisé à utiliser cette commande.', adminActionRequired: 'Vous devez être administrateur pour cette action.', actionNotAuthorized: 'Vous n’êtes pas autorisé pour cette action.', playModeAdminOnly: 'Le play mode est activé.\nSeuls les administrateurs et utilisateurs autorisés peuvent lancer la lecture.' } },
  de: { playback: { voiceChatInactiveWarning: '⚠️ Der Sprachchat ist in dieser Gruppe noch nicht aktiv. Starte zuerst den Sprach-/Videochat und nutze dann /play erneut.' }, filters: { botNotAdmin: 'Der Bot ist in diesem Chat kein Administrator.\nGib dem Bot die Berechtigung, Benutzer einzuladen.', botAdminVerifyFailed: 'Administratorstatus des Bots konnte nicht geprüft werden.', botMissingInvite: 'Der Bot darf keine Benutzer einladen.', botNotAdminReload: 'Der Bot ist in diesem Chat kein Administrator.\nNutze /reload, um den Admin-Cache zu aktualisieren.', adminRequired: 'Du musst Administrator sein, um diesen Befehl zu verwenden.', notAuthorized: 'Du bist für diesen Befehl nicht autorisiert.', adminActionRequired: 'Du musst Administrator sein, um diese Aktion zu verwenden.', actionNotAuthorized: 'Du bist für diese Aktion nicht autorisiert.', playModeAdminOnly: 'Play mode ist aktiviert.\nNur Administratoren und autorisierte Benutzer können Wiedergabe starten.' } },
  pt: { playback: { voiceChatInactiveWarning: '⚠️ O chat de voz ainda não está ativo neste grupo. Inicie primeiro o chat de voz/vídeo e depois use /play novamente.' }, filters: { botNotAdmin: 'O bot não é administrador neste chat.\nPromova o bot com permissão para convidar usuários.', botAdminVerifyFailed: 'Não foi possível verificar o status de administrador do bot.', botMissingInvite: 'O bot não tem permissão para convidar usuários.', botNotAdminReload: 'O bot não é administrador neste chat.\nUse /reload para atualizar o cache de admins.', adminRequired: 'Você precisa ser administrador para usar este comando.', notAuthorized: 'Você não está autorizado a usar este comando.', adminActionRequired: 'Você precisa ser administrador para esta ação.', actionNotAuthorized: 'Você não está autorizado para esta ação.', playModeAdminOnly: 'Play mode está ativado.\nApenas administradores e usuários autorizados podem iniciar a reprodução.' } },
  ar: { playback: { voiceChatInactiveWarning: '⚠️ الدردشة الصوتية غير مفعلة بعد في هذه المجموعة. ابدأ أولًا دردشة صوتية/فيديو ثم أعد استخدام /play.' }, filters: { botNotAdmin: 'البوت ليس مشرفًا في هذه المحادثة.\nقم بترقية البوت مع صلاحية دعوة المستخدمين.', botAdminVerifyFailed: 'تعذر التحقق من حالة مشرف البوت.', botMissingInvite: 'لا يملك البوت صلاحية دعوة المستخدمين.', botNotAdminReload: 'البوت ليس مشرفًا في هذه المحادثة.\nاستخدم /reload لتحديث كاش المشرفين.', adminRequired: 'يجب أن تكون مشرفًا لاستخدام هذا الأمر.', notAuthorized: 'أنت غير مصرح لاستخدام هذا الأمر.', adminActionRequired: 'يجب أن تكون مشرفًا لاستخدام هذا الإجراء.', actionNotAuthorized: 'أنت غير مصرح لهذا الإجراء.', playModeAdminOnly: 'وضع التشغيل مفعل.\nيمكن للمشرفين والمستخدمين المصرح لهم فقط بدء التشغيل.' } },
  tr: { playback: { voiceChatInactiveWarning: '⚠️ Bu grupta sesli sohbet henüz aktif değil. Önce sesli/görüntülü sohbet başlatın, ardından /play kullanın.' }, filters: { botNotAdmin: 'Bot bu sohbette yönetici değil.\nBotu kullanıcı davet etme izniyle yönetici yap.', botAdminVerifyFailed: 'Bot yönetici durumu doğrulanamadı.', botMissingInvite: 'Botun kullanıcı davet etme izni yok.', botNotAdminReload: 'Bot bu sohbette yönetici değil.\nAdmin önbelleğini yenilemek için /reload kullan.', adminRequired: 'Bu komutu kullanmak için yönetici olmalısın.', notAuthorized: 'Bu komutu kullanmaya yetkili değilsin.', adminActionRequired: 'Bu eylem için yönetici olmalısın.', actionNotAuthorized: 'Bu eylem için yetkili değilsin.', playModeAdminOnly: 'Play mode etkin.\nSadece yöneticiler ve yetkili kullanıcılar oynatmayı başlatabilir.' } },
  ko: { playback: { voiceChatInactiveWarning: '⚠️ 이 그룹에서 음성 채팅이 아직 활성화되지 않았습니다. 먼저 음성/영상 채팅을 시작한 뒤 /play를 사용하세요.' }, filters: { botNotAdmin: '이 채팅에서 봇이 관리자가 아닙니다.\n사용자 초대 권한과 함께 봇을 관리자로 승격하세요.', botAdminVerifyFailed: '봇 관리자 상태를 확인할 수 없습니다.', botMissingInvite: '봇에 사용자 초대 권한이 없습니다.', botNotAdminReload: '이 채팅에서 봇이 관리자가 아닙니다.\n/reload로 관리자 캐시를 새로고침하세요.', adminRequired: '이 명령을 사용하려면 관리자여야 합니다.', notAuthorized: '이 명령을 사용할 권한이 없습니다.', adminActionRequired: '이 작업을 사용하려면 관리자여야 합니다.', actionNotAuthorized: '이 작업을 사용할 권한이 없습니다.', playModeAdminOnly: 'Play mode가 활성화되었습니다.\n관리자와 인증된 사용자만 재생을 시작할 수 있습니다.' } },
  zh: { playback: { voiceChatInactiveWarning: '⚠️ 此群组的语音聊天尚未开启。请先开启语音/视频聊天，然后再使用 /play。' }, filters: { botNotAdmin: '机器人不是此聊天的管理员。\n请授予机器人邀请用户权限。', botAdminVerifyFailed: '无法验证机器人管理员状态。', botMissingInvite: '机器人没有邀请用户权限。', botNotAdminReload: '机器人不是此聊天的管理员。\n使用 /reload 刷新管理员缓存。', adminRequired: '你必须是管理员才能使用此命令。', notAuthorized: '你无权使用此命令。', adminActionRequired: '你必须是管理员才能执行此操作。', actionNotAuthorized: '你无权执行此操作。', playModeAdminOnly: 'Play mode 已启用。\n只有管理员和已授权用户可以开始播放。' } },
};

for (const [code, override] of Object.entries(filterTranslations)) {
  translations[code] = mergeDeep(translations[code], override);
}
