import { reloadAdminCacheHandler } from './admins.js';
import { addAuthHandler, authListHandler, removeAuthHandler } from './auth.js';
import { broadcastHandler, cancelBroadcastHandler } from './broadcast.js';
import { vcPlayCallbackHandler } from './callbacks.js';
import { clearAssistantsHandler, devActiveVcHandler, leaveAllHandler, loggerToggleHandler } from './devs.js';
import { helpCallback, languageMenuHandler, languageSelectHandler, startHandler } from './help.js';
import { loopHandler, muteHandler, pauseHandler, playHandler, queueHandler, removeHandler, resumeHandler, skipHandler, speedHandler, stopHandler, unmuteHandler, youtubeSelectionPageHandler, youtubeSelectionPickHandler } from './playback.js';
import { addToPlaylistHandler, createPlaylistHandler, deletePlaylistHandler, myPlaylistsHandler, playlistInfoHandler, removeFromPlaylistHandler } from './playlists.js';
import { noopHandler, pingHandler, privacyHandler, settingsHandler, shellHandler, statsHandler } from './misc.js';

export function loadHandlers(bot) {
  bot.command('start', startHandler);
  bot.command('help', async (ctx) => {
    await startHandler(ctx);
  });
  bot.command(['language', 'lang'], languageMenuHandler);
  bot.command('ping', pingHandler);
  bot.command(['play', 'p'], (ctx) => playHandler(ctx, false));
  bot.command(['vplay', 'v'], (ctx) => playHandler(ctx, true));
  bot.command('queue', queueHandler);
  bot.command('skip', skipHandler);
  bot.command(['stop', 'end'], stopHandler);
  bot.command('pause', pauseHandler);
  bot.command('resume', resumeHandler);
  bot.command('remove', removeHandler);
  bot.command('loop', loopHandler);
  bot.command('mute', muteHandler);
  bot.command('unmute', unmuteHandler);
  bot.command('speed', speedHandler);
  bot.command(['av', 'active_vc', 'activevc'], devActiveVcHandler);
  bot.command(['cplist', 'createplaylist'], createPlaylistHandler);
  bot.command('deleteplaylist', deletePlaylistHandler);
  bot.command(['addtoplaylist', 'addtoplist'], addToPlaylistHandler);
  bot.command(['removefromplaylist', 'rmplist'], removeFromPlaylistHandler);
  bot.command(['plistinfo', 'playlistinfo'], playlistInfoHandler);
  bot.command(['myplaylists', 'myplist'], myPlaylistsHandler);
  bot.command('stats', statsHandler);
  bot.command('settings', settingsHandler);
  bot.command('privacy', privacyHandler);
  bot.command('reload', reloadAdminCacheHandler);
  bot.command(['authlist', 'auths', 'auth'], authListHandler);
  bot.command('addauth', addAuthHandler);
  bot.command(['removeauth', 'rmauth'], removeAuthHandler);
  bot.command(['broadcast', 'gcast'], broadcastHandler);
  bot.command(['stop_broadcast', 'stop_gcast'], cancelBroadcastHandler);
  bot.command('logger', loggerToggleHandler);
  bot.command('sh', shellHandler);
  bot.command(['clearass', 'clearassistants'], clearAssistantsHandler);
  bot.command('leaveall', leaveAllHandler);
  bot.command('seek', noopHandler);
  bot.callbackQuery('language_menu', languageMenuHandler);
  bot.callbackQuery(/^lang_/, languageSelectHandler);
  bot.callbackQuery('settings_menu', settingsHandler);
  bot.callbackQuery(/^help_/, helpCallback);
  bot.callbackQuery(/^ytpage:/, youtubeSelectionPageHandler);
  bot.callbackQuery(/^ytpick:/, youtubeSelectionPickHandler);
  bot.callbackQuery(/^(?:vcplay_|play_)/, vcPlayCallbackHandler);
}
